// The workspace repository's view model — the sheaf storage protocol's messages, generated by
// protobuf-es from schema/proto/themis/rpc/sheaf.proto and schema/proto/themis/sheaf/models/refdoc.proto.
// The Workbench's workspace-repository methods reply with the sheaf service's own messages, so these
// are the BFF↔frontend shapes as they stand; app code imports them from here rather than the
// generated paths.

export * from "@/gen/themis/rpc/sheaf_pb";
export * from "@/gen/themis/sheaf/models/refdoc_pb";
