"""S11b-0 smoke: the pubmed_proto wheel imports and its converters work in themis.

litcache's bibliographic metadata (S11b) is pubmed_proto canonical JSON: the
efetch path is XML → proto (`xml_converter`) → pydantic (`pydantic_converter`) →
`model_dump_json`, and non-PubMed sources (Crossref, bioRxiv, upload) construct the
pydantic `models.PubmedArticle` directly. This proves the wheelhouse dependency
resolves and the three seams litcache needs work: the bidirectional proto↔pydantic
converter, pydantic JSON emission, and JSON validation.

It also pins the canonical-JSON convention litcache writes: `model_dump_json(
exclude_none=True)` — unset optionals are omitted, list fields serialize even when
empty, and the result round-trips back through `model_validate_json`. The wheel is
generated by xsd-former from the NLM PubMed DTD; xml_converter (XML→proto) is
exercised against a real efetch response in the S11b-1 resolver slice.
"""

from __future__ import annotations

import datetime
import json

from pubmed_proto import models, pydantic_converter


def _to_canonical_json(model: models.PubmedArticle) -> str:
    """Emit metadata.json bytes with litcache's pinned convention.

    `exclude_none=True`: unset optionals are omitted; list fields still serialize
    when empty. A change to this is a deliberate, visible edit.
    """
    return model.model_dump_json(exclude_none=True)


def _sample_article() -> models.PubmedArticle:
    """A representative PubmedArticle built from the pydantic side.

    This is the shape the non-PubMed synthesis / Crossref-mapping slices produce
    by hand; `pub_date` is naive because the proto Timestamp round-trip
    (`FromDatetime`/`ToDatetime`) is naive-UTC, so a naive value round-trips exactly.
    """
    return models.PubmedArticle(
        medline_citation=models.MedlineCitation(
            status=models.MedlineCitation_Status.STATUS_MEDLINE,
            pmid=models.Pmid(version='1', value='12345678'),
            article=models.Article(
                pub_model=models.Article_PubModel.PUB_MODEL_ELECTRONIC,
                journal=models.Journal(
                    journal_issue=models.JournalIssue(
                        cited_medium=models.JournalIssue_CitedMedium.CITED_MEDIUM_INTERNET,
                        pub_date=datetime.datetime(2026, 1, 1),  # noqa: DTZ001 — proto Timestamp round-trip is naive-UTC
                    ),
                    title='Journal of Smoke Tests',
                ),
                article_title=models.ArticleTitle(value='A representative article'),
                abstract=models.Abstract(abstract_text=[models.AbstractText(value='Abstract body.')]),
            ),
        ),
        pubmed_data=models.PubmedData(
            publication_status='ppublish',
            article_id_list=[
                models.ArticleId(id_type=models.ArticleId_IdType.ID_TYPE_DOI, value='10.1234/smoke'),
                models.ArticleId(id_type=models.ArticleId_IdType.ID_TYPE_PUBMED, value='12345678'),
            ],
        ),
    )


def test_proto_pydantic_round_trip() -> None:
    """Proto round-trip is lossless: model → proto → model, both directions."""
    model = _sample_article()
    proto = pydantic_converter.PubmedArticle_to_proto(model)
    # The proto is the xml_converter output shape the efetch path feeds back in.
    assert proto.medline_citation.pmid.value == '12345678'
    restored = pydantic_converter.PubmedArticle_from_proto(proto)
    assert restored == model


def test_metadata_json_convention_and_validation() -> None:
    """The pinned dump convention emits snake_case JSON that validates back."""
    model = _sample_article()
    blob = _to_canonical_json(model)
    doc = json.loads(blob)

    # snake_case field names (proto/DTD-faithful), nested structure intact.
    assert doc['medline_citation']['pmid']['value'] == '12345678'
    # exclude_none drops unset optionals: ArticleTitle.{book,sec,part} are None.
    assert set(doc['medline_citation']['article']['article_title']) == {'value'}
    # cross-ids are carried in pubmed_data.article_id_list (S11b-1 reads them).
    id_types = {a['id_type'] for a in doc['pubmed_data']['article_id_list']}
    assert id_types == {'doi', 'pubmed'}

    # round-trips: the written bytes validate straight back to an equal model.
    assert models.PubmedArticle.model_validate_json(blob) == model
