// The widget payloads a working document embeds, and the option that marks a message as one —
// generated by protobuf-es from schema/proto/themis/widgets/models/. App code imports them from here
// rather than the generated paths.

export * from "@/gen/themis/widgets/models/checklist_pb";
export * from "@/gen/themis/widgets/models/widget_pb";
