"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `auth` service: session-token resolution (docs/plans/self-hosted-sandbox.md §7). The store
forwards a sandbox's per-session token; the auth service — the sole reader of the token store —
resolves it to the Project + Analysis it grants access to. This proto is the source of truth (the
contract); `regen` (buf generate) emits the themis/rpc/auth stubs each consumer imports — the server
subclasses the servicer base, a caller uses the stub.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import auth_pb2 as _auth_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AuthStub:
    """The auth service: resolve a session token to the Project + Analysis binding it grants."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AuthAsyncStub: ...
    ResolveSession: _grpc.UnaryUnaryMultiCallable[_auth_pb2.ResolveTokenRequest, _auth_pb2.SessionContext]
    """Resolve a session token to its binding. An invalid, revoked, or expired token is a
    PERMISSION_DENIED the server adds — a transport-level rejection, not a modelled body this slice.
    """

@_typing.type_check_only
class AuthAsyncStub(AuthStub):
    """The auth service: resolve a session token to the Project + Analysis binding it grants."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    ResolveSession: _aio.UnaryUnaryMultiCallable[_auth_pb2.ResolveTokenRequest, _auth_pb2.SessionContext]  # type: ignore[assignment]
    """Resolve a session token to its binding. An invalid, revoked, or expired token is a
    PERMISSION_DENIED the server adds — a transport-level rejection, not a modelled body this slice.
    """

class AuthServicer(metaclass=_abc_1.ABCMeta):
    """The auth service: resolve a session token to the Project + Analysis binding it grants."""

    @_abc_1.abstractmethod
    def ResolveSession(
        self,
        request: _auth_pb2.ResolveTokenRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_pb2.SessionContext, _abc.Awaitable[_auth_pb2.SessionContext]]:
        """Resolve a session token to its binding. An invalid, revoked, or expired token is a
        PERMISSION_DENIED the server adds — a transport-level rejection, not a modelled body this slice.
        """

def add_AuthServicer_to_server(servicer: AuthServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
