# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: themis/rpc/auth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'themis/rpc/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15themis/rpc/auth.proto\x12\x0fthemis.rpc.auth\",\n\x13ResolveTokenRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"9\n\x0eSessionContext\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61nalysis_id\x18\x02 \x01(\t2_\n\x04\x41uth\x12W\n\x0eResolveSession\x12$.themis.rpc.auth.ResolveTokenRequest\x1a\x1f.themis.rpc.auth.SessionContextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'themis.rpc.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVETOKENREQUEST']._serialized_start=42
  _globals['_RESOLVETOKENREQUEST']._serialized_end=86
  _globals['_SESSIONCONTEXT']._serialized_start=88
  _globals['_SESSIONCONTEXT']._serialized_end=145
  _globals['_AUTH']._serialized_start=147
  _globals['_AUTH']._serialized_end=242
# @@protoc_insertion_point(module_scope)
