# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import auth_pb2 as themis_dot_rpc_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthStub:
    """The auth service: resolve a session token to the Project + Analysis binding it grants.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveSession = channel.unary_unary(
                '/themis.rpc.auth.Auth/ResolveSession',
                request_serializer=themis_dot_rpc_dot_auth__pb2.ResolveTokenRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_auth__pb2.SessionContext.FromString,
                _registered_method=True)


class AuthServicer:
    """The auth service: resolve a session token to the Project + Analysis binding it grants.
    """

    def ResolveSession(self, request, context):
        """Resolve a session token to its binding. An invalid, revoked, or expired token is a
        PERMISSION_DENIED the server adds — a transport-level rejection, not a modelled body this slice.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSession,
                    request_deserializer=themis_dot_rpc_dot_auth__pb2.ResolveTokenRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_auth__pb2.SessionContext.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.auth.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.auth.Auth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Auth:
    """The auth service: resolve a session token to the Project + Analysis binding it grants.
    """

    @staticmethod
    def ResolveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.auth.Auth/ResolveSession',
            themis_dot_rpc_dot_auth__pb2.ResolveTokenRequest.SerializeToString,
            themis_dot_rpc_dot_auth__pb2.SessionContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
