"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
clinvar: NCBI ClinVar — the queried allele's own record with its per-submission evidence, the
gene's classified pool, and every record at one coding span. Design: docs/design/evidence-interfaces.md.

Modelled from:
  NCBI ClinVar E-utilities — `efetch` (the VCV record) and `esearch` -> `esummary` (the pooled
    searches): `ClinVarRecord`, `ClinVarSubmission`, `ClinVarObservation` and `ClinVarZygosityCount`
    carry the record's fields under ClinVar's own names and attribute tokens; `variation_archive` is
    clinvar-proto's generated record type, whose schema this module carries a copy of
    (clinvar_proto/clinvar.proto).
  SVCv4 SM19 / SM3 (docs/design/svcv4-interpretations.md § "Which ClinVar classifications count as a
    pathogenic assertion"): the membership gate `esearch_term` encodes, and the field-to-code mapping
    in the comments; no message models an SVCv4 vocabulary.
  This interface's own design: both request messages, the census fields (`total_in_gene`,
    `considered_in_gene`, `pool_truncated`, `records_with_unparsed_hgvs`, `esearch_term`, and
    `SearchCodingSpan`'s counterparts), and `CodingRegion` / `CodingCoordinate` / `CodingSpan`, which
    model HGVS c. coordinate grammar.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto. The c. coordinate types are this contract's own.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import clinvar_pb2 as _clinvar_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ClinVarStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ClinVarAsyncStub: ...
    DescribeVariant: _grpc.UnaryUnaryMultiCallable[_clinvar_pb2.DescribeVariantRequest, _clinvar_pb2.DescribeVariantResponse]
    """NCBI ClinVar, keyed on the variation accession Variant.Normalize's crosswalk named. The
    accession's own record with its per-submission evidence, and the gene's records ClinVar
    classifies pathogenic at the requested review-status floor -> the P/LP density and the pathogenic
    half of the *_INF candidate set (eligibility is the model's, SM19). The gene pool is P/LP by
    construction, so the benign and VUS arms of the *_INF rules are SearchCodingSpan's, not this
    rpc's. See DescribeVariantResponse.
    """
    SearchCodingSpan: _grpc.UnaryUnaryMultiCallable[_clinvar_pb2.SearchCodingSpanRequest, _clinvar_pb2.SearchCodingSpanResponse]
    """VariantValidator (the exon table) -> NCBI ClinVar. Every germline record ClinVar holds at
    one c. span of one transcript, of every classification, with its review stars and c. coordinates
    -> the *_INF candidate set at a codon or an exon, benign and VUS arms included. See
    SearchCodingSpanResponse.
    """

@_typing.type_check_only
class ClinVarAsyncStub(ClinVarStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribeVariant: _aio.UnaryUnaryMultiCallable[_clinvar_pb2.DescribeVariantRequest, _clinvar_pb2.DescribeVariantResponse]  # type: ignore[assignment]
    """NCBI ClinVar, keyed on the variation accession Variant.Normalize's crosswalk named. The
    accession's own record with its per-submission evidence, and the gene's records ClinVar
    classifies pathogenic at the requested review-status floor -> the P/LP density and the pathogenic
    half of the *_INF candidate set (eligibility is the model's, SM19). The gene pool is P/LP by
    construction, so the benign and VUS arms of the *_INF rules are SearchCodingSpan's, not this
    rpc's. See DescribeVariantResponse.
    """
    SearchCodingSpan: _aio.UnaryUnaryMultiCallable[_clinvar_pb2.SearchCodingSpanRequest, _clinvar_pb2.SearchCodingSpanResponse]  # type: ignore[assignment]
    """VariantValidator (the exon table) -> NCBI ClinVar. Every germline record ClinVar holds at
    one c. span of one transcript, of every classification, with its review stars and c. coordinates
    -> the *_INF candidate set at a codon or an exon, benign and VUS arms included. See
    SearchCodingSpanResponse.
    """

class ClinVarServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def DescribeVariant(
        self,
        request: _clinvar_pb2.DescribeVariantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_clinvar_pb2.DescribeVariantResponse, _abc.Awaitable[_clinvar_pb2.DescribeVariantResponse]]:
        """NCBI ClinVar, keyed on the variation accession Variant.Normalize's crosswalk named. The
        accession's own record with its per-submission evidence, and the gene's records ClinVar
        classifies pathogenic at the requested review-status floor -> the P/LP density and the pathogenic
        half of the *_INF candidate set (eligibility is the model's, SM19). The gene pool is P/LP by
        construction, so the benign and VUS arms of the *_INF rules are SearchCodingSpan's, not this
        rpc's. See DescribeVariantResponse.
        """

    @_abc_1.abstractmethod
    def SearchCodingSpan(
        self,
        request: _clinvar_pb2.SearchCodingSpanRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_clinvar_pb2.SearchCodingSpanResponse, _abc.Awaitable[_clinvar_pb2.SearchCodingSpanResponse]]:
        """VariantValidator (the exon table) -> NCBI ClinVar. Every germline record ClinVar holds at
        one c. span of one transcript, of every classification, with its review stars and c. coordinates
        -> the *_INF candidate set at a codon or an exon, benign and VUS arms included. See
        SearchCodingSpanResponse.
        """

def add_ClinVarServicer_to_server(servicer: ClinVarServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
