# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import clinvar_pb2 as themis_dot_rpc_dot_clinvar__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/clinvar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClinVarStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeVariant = channel.unary_unary(
                '/themis.rpc.clinvar.ClinVar/DescribeVariant',
                request_serializer=themis_dot_rpc_dot_clinvar__pb2.DescribeVariantRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_clinvar__pb2.DescribeVariantResponse.FromString,
                _registered_method=True)
        self.SearchCodingSpan = channel.unary_unary(
                '/themis.rpc.clinvar.ClinVar/SearchCodingSpan',
                request_serializer=themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanResponse.FromString,
                _registered_method=True)


class ClinVarServicer:
    """Missing associated documentation comment in .proto file."""

    def DescribeVariant(self, request, context):
        """NCBI ClinVar, keyed on the variation accession Variant.Normalize's crosswalk named. The
        accession's own record with its per-submission evidence, and the gene's records ClinVar
        classifies pathogenic at the requested review-status floor -> the P/LP density and the pathogenic
        half of the *_INF candidate set (eligibility is the model's, SM19). The gene pool is P/LP by
        construction, so the benign and VUS arms of the *_INF rules are SearchCodingSpan's, not this
        rpc's. See DescribeVariantResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCodingSpan(self, request, context):
        """VariantValidator (the exon table) -> NCBI ClinVar. Every germline record ClinVar holds at
        one c. span of one transcript, of every classification, with its review stars and c. coordinates
        -> the *_INF candidate set at a codon or an exon, benign and VUS arms included. See
        SearchCodingSpanResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClinVarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeVariant': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeVariant,
                    request_deserializer=themis_dot_rpc_dot_clinvar__pb2.DescribeVariantRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_clinvar__pb2.DescribeVariantResponse.SerializeToString,
            ),
            'SearchCodingSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCodingSpan,
                    request_deserializer=themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.clinvar.ClinVar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.clinvar.ClinVar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClinVar:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribeVariant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.clinvar.ClinVar/DescribeVariant',
            themis_dot_rpc_dot_clinvar__pb2.DescribeVariantRequest.SerializeToString,
            themis_dot_rpc_dot_clinvar__pb2.DescribeVariantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCodingSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.clinvar.ClinVar/SearchCodingSpan',
            themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanRequest.SerializeToString,
            themis_dot_rpc_dot_clinvar__pb2.SearchCodingSpanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
