"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
cspec: the ClinGen Criteria Specification Registry — what an expert panel wrote its own criteria
to say for a gene. Design: docs/design/evidence-interfaces.md.

Modelled from:
  ClinGen Criteria Specification Registry (CSpec) — its gene, specification and rule-set records:
    `VcepSpecification`, `SpecifiedEntity`, `SpecificationCitation`, `SpecificationReference`,
    `CriterionNote`, `StrengthSpecification`, `CriterionSpecification` and `SpecificationAttachment`
    carry its fields under its names; the codes and the strength ladder are ACMG/AMP 2015's.
  This interface's own design: `ListSpecificationsRequest`, `SpecificationCoverage`,
    `SpecificationStatus` (derived over the registry's state history and legacy flags), and
    `Applicability` (the registry's several wordings folded onto one determination).
  SVCv4: nothing here models it — the registry serves no SVCv4 profile.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import cspec_pb2 as _cspec_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class CspecStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> CspecAsyncStub: ...
    ListSpecifications: _grpc.UnaryUnaryMultiCallable[_cspec_pb2.ListSpecificationsRequest, _cspec_pb2.ListSpecificationsResponse]
    """ClinGen CSpec Registry: every criteria specification whose rule set names the gene, with
    each ACMG/AMP-2015 criterion's applicability, per-strength gene-specific wording and thresholds,
    the panel's cited works and attachments, and the DOI + version a quotation is attributed to.
    Reduced across nothing and selected from by nothing: a gene can be covered by a multi-gene legacy
    document and by the per-gene one carved out of it, and which governs is each one's `status`. A
    gene no panel has specified and a symbol the registry's gene table has no entry for are distinct
    answers (`coverage`), neither an error. The derived leaves are `status` (over the document's
    state history and its two legacy flags), the registry URLs and the rendered author strings.

    SM3 ranks a curated VCEP threshold first among its DAFT methods, and this is how that method is
    reached. It is NOT an SVCv4 profile: the codes, strengths and points here are ACMG/AMP-2015 and
    the panel's own, and a threshold enters SM3's ordering at the rung ITS derivation earns rather
    than at method 1 because a VCEP published it. See ListSpecificationsResponse.
    """

@_typing.type_check_only
class CspecAsyncStub(CspecStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    ListSpecifications: _aio.UnaryUnaryMultiCallable[_cspec_pb2.ListSpecificationsRequest, _cspec_pb2.ListSpecificationsResponse]  # type: ignore[assignment]
    """ClinGen CSpec Registry: every criteria specification whose rule set names the gene, with
    each ACMG/AMP-2015 criterion's applicability, per-strength gene-specific wording and thresholds,
    the panel's cited works and attachments, and the DOI + version a quotation is attributed to.
    Reduced across nothing and selected from by nothing: a gene can be covered by a multi-gene legacy
    document and by the per-gene one carved out of it, and which governs is each one's `status`. A
    gene no panel has specified and a symbol the registry's gene table has no entry for are distinct
    answers (`coverage`), neither an error. The derived leaves are `status` (over the document's
    state history and its two legacy flags), the registry URLs and the rendered author strings.

    SM3 ranks a curated VCEP threshold first among its DAFT methods, and this is how that method is
    reached. It is NOT an SVCv4 profile: the codes, strengths and points here are ACMG/AMP-2015 and
    the panel's own, and a threshold enters SM3's ordering at the rung ITS derivation earns rather
    than at method 1 because a VCEP published it. See ListSpecificationsResponse.
    """

class CspecServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def ListSpecifications(
        self,
        request: _cspec_pb2.ListSpecificationsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_cspec_pb2.ListSpecificationsResponse, _abc.Awaitable[_cspec_pb2.ListSpecificationsResponse]]:
        """ClinGen CSpec Registry: every criteria specification whose rule set names the gene, with
        each ACMG/AMP-2015 criterion's applicability, per-strength gene-specific wording and thresholds,
        the panel's cited works and attachments, and the DOI + version a quotation is attributed to.
        Reduced across nothing and selected from by nothing: a gene can be covered by a multi-gene legacy
        document and by the per-gene one carved out of it, and which governs is each one's `status`. A
        gene no panel has specified and a symbol the registry's gene table has no entry for are distinct
        answers (`coverage`), neither an error. The derived leaves are `status` (over the document's
        state history and its two legacy flags), the registry URLs and the rendered author strings.

        SM3 ranks a curated VCEP threshold first among its DAFT methods, and this is how that method is
        reached. It is NOT an SVCv4 profile: the codes, strengths and points here are ACMG/AMP-2015 and
        the panel's own, and a threshold enters SM3's ordering at the rung ITS derivation earns rather
        than at method 1 because a VCEP published it. See ListSpecificationsResponse.
        """

def add_CspecServicer_to_server(servicer: CspecServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
