# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import gene_disease_pb2 as themis_dot_rpc_dot_gene__disease__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/gene_disease_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneDiseaseStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeGene = channel.unary_unary(
                '/themis.rpc.gene_disease.GeneDisease/DescribeGene',
                request_serializer=themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneResponse.FromString,
                _registered_method=True)


class GeneDiseaseServicer:
    """Missing associated documentation comment in .proto file."""

    def DescribeGene(self, request, context):
        """ClinGen validity/dosage + GenCC + PanelApp AU, keyed under MONDO's subclass closure.
        Lists every gene-disease entity curated for the gene: one element per (source, MONDO term,
        inheritance) a curator asserts, with its label, its classification on the harmonised rank, the
        gate level that classification reads as, its mechanism narratives and its source. Where a source
        states one entity several times — GenCC files one row per submitter — they reduce to its
        strongest classification on the published rank, an aggregation under a fixed vocabulary, with
        each assertion kept. Across entities the rpc reduces nothing and selects nothing: which curated
        entity a presentation belongs to is the analyst's call (SM21), and the level the gate reads is
        that entity's, not the gene's (SM18). Name the entity you established as `mondo_id` +
        `inheritance` and the rpc resolves it: the requested term's own curations decide wherever the
        gene is curated for that term, and only where it is not does a curated MONDO subclass descendant
        of it resolve. It answers with the entities that name your entity, and FAILED_PRECONDITION where
        the term selects several of the gene's or none of them — never the nearest. A gene the tables do
        not carry and a gene they carry with no validity assertion are distinct answers (`coverage`).
        Classification, gate level, inheritance and mechanism narratives are per entity; the
        haploinsufficiency score, the gain-of-function veto and PanelApp's mode of inheritance are per
        gene. See DescribeGeneResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneDiseaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeGene': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeGene,
                    request_deserializer=themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.gene_disease.GeneDisease', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.gene_disease.GeneDisease', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneDisease:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribeGene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.gene_disease.GeneDisease/DescribeGene',
            themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneRequest.SerializeToString,
            themis_dot_rpc_dot_gene__disease__pb2.DescribeGeneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
