# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: themis/rpc/gnomad.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'themis/rpc/gnomad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from themis.evidence.models import evidence_pb2 as themis_dot_evidence_dot_models_dot_evidence__pb2
from themis.rpc import sandbox_options_pb2 as themis_dot_rpc_dot_sandbox__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17themis/rpc/gnomad.proto\x12\x11themis.rpc.gnomad\x1a\x1cgoogle/protobuf/struct.proto\x1a%themis/evidence/models/evidence.proto\x1a themis/rpc/sandbox_options.proto\"W\n\x16\x44\x65scribeVariantRequest\x12\x11\n\tgnomad_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x19\n\x11\x63ooccurrence_with\x18\x03 \x01(\t\"w\n\x17\x44\x65scribeVariantResponse\x12$\n\x03raw\x18\x0f \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x36\n\nprovenance\x18\x10 \x03(\x0b\x32\".themis.evidence.models.Provenance2x\n\x06Gnomad\x12n\n\x0f\x44\x65scribeVariant\x12).themis.rpc.gnomad.DescribeVariantRequest\x1a*.themis.rpc.gnomad.DescribeVariantResponse\"\x04\x90\xb5\x18\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'themis.rpc.gnomad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GNOMAD'].methods_by_name['DescribeVariant']._loaded_options = None
  _globals['_GNOMAD'].methods_by_name['DescribeVariant']._serialized_options = b'\220\265\030\001'
  _globals['_DESCRIBEVARIANTREQUEST']._serialized_start=149
  _globals['_DESCRIBEVARIANTREQUEST']._serialized_end=236
  _globals['_DESCRIBEVARIANTRESPONSE']._serialized_start=238
  _globals['_DESCRIBEVARIANTRESPONSE']._serialized_end=357
  _globals['_GNOMAD']._serialized_start=359
  _globals['_GNOMAD']._serialized_end=479
# @@protoc_insertion_point(module_scope)
