"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
gnomad: the Genome Aggregation Database — population allele frequencies and the observation
counts POP_FRQ and POP_HMZ rest on. Design: docs/design/evidence-interfaces.md.

Modelled from:
  gnomAD GraphQL API (`variant` query): `DescribeVariantResponse.raw` is its payload verbatim — no
    field of it is typed here.
  SVCv4 SM3 frequency (docs/design/svcv4-interpretations.md § "Frequency: which figure, and what
    disqualifies one"): the field-to-code mapping in the comments below; no message models it.
  This interface's own design: `DescribeVariantRequest` — the id shape precondition and the dataset
    allowlist.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import gnomad_pb2 as _gnomad_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GnomadStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GnomadAsyncStub: ...
    DescribeVariant: _grpc.UnaryUnaryMultiCallable[_gnomad_pb2.DescribeVariantRequest, _gnomad_pb2.DescribeVariantResponse]
    """gnomAD: joint faf95 + the per-dataset filters -> POP_FRQ, homozygote_count and
    hemizygote_count -> POP_HMZ, co-occurrence, pext/LOEUF/constraint ->
    Transcript.AssessExonRelevance, STR.
    See DescribeVariantResponse.
    """

@_typing.type_check_only
class GnomadAsyncStub(GnomadStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribeVariant: _aio.UnaryUnaryMultiCallable[_gnomad_pb2.DescribeVariantRequest, _gnomad_pb2.DescribeVariantResponse]  # type: ignore[assignment]
    """gnomAD: joint faf95 + the per-dataset filters -> POP_FRQ, homozygote_count and
    hemizygote_count -> POP_HMZ, co-occurrence, pext/LOEUF/constraint ->
    Transcript.AssessExonRelevance, STR.
    See DescribeVariantResponse.
    """

class GnomadServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def DescribeVariant(
        self,
        request: _gnomad_pb2.DescribeVariantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_gnomad_pb2.DescribeVariantResponse, _abc.Awaitable[_gnomad_pb2.DescribeVariantResponse]]:
        """gnomAD: joint faf95 + the per-dataset filters -> POP_FRQ, homozygote_count and
        hemizygote_count -> POP_HMZ, co-occurrence, pext/LOEUF/constraint ->
        Transcript.AssessExonRelevance, STR.
        See DescribeVariantResponse.
        """

def add_GnomadServicer_to_server(servicer: GnomadServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
