"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `hello` service: a trivial session-token-authed internal service. `sayHello` resolves the
request's session token to its Project + Analysis binding and echoes the caller's note against it.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import hello_pb2 as _hello_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class HelloStub:
    """The hello service: echo the caller's note against its resolved session binding."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> HelloAsyncStub: ...
    SayHello: _grpc.UnaryUnaryMultiCallable[_hello_pb2.SayHelloRequest, _hello_pb2.SayHelloResponse]
    """Resolve the request's session token and echo the note against the bound Analysis."""

@_typing.type_check_only
class HelloAsyncStub(HelloStub):
    """The hello service: echo the caller's note against its resolved session binding."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    SayHello: _aio.UnaryUnaryMultiCallable[_hello_pb2.SayHelloRequest, _hello_pb2.SayHelloResponse]  # type: ignore[assignment]
    """Resolve the request's session token and echo the note against the bound Analysis."""

class HelloServicer(metaclass=_abc_1.ABCMeta):
    """The hello service: echo the caller's note against its resolved session binding."""

    @_abc_1.abstractmethod
    def SayHello(
        self,
        request: _hello_pb2.SayHelloRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_hello_pb2.SayHelloResponse, _abc.Awaitable[_hello_pb2.SayHelloResponse]]:
        """Resolve the request's session token and echo the note against the bound Analysis."""

def add_HelloServicer_to_server(servicer: HelloServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
