"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `Literature` service — the literature evidence layer's read surface for the workbench,
(docs/design/document-pane.md). It owns litcache resolution — given a canonical doc_id it names
the GCS object for a rendering, the PDF, or an associated file, and it locates a citation's quote
within a chosen representation (offsets in markdown; a page region in a PDF). This proto is the
source of truth; `regen` (buf generate) emits the themis/rpc/literature stubs — the server
subclasses the servicer base, a caller uses the stub.

Two consumers: the BFF (service-to-service) calls DescribePaper/ResolveContent/Locate and serves
the named object itself; the sandbox agent calls Validate at authoring time. The corpus is shared
(litcache is not session-scoped yet — entitlement is a deferred non-goal, literature-evidence-layer.md),
so the read rpcs carry no session binding. MaybeIngestPapers is the exception, stated where it is
declared rather than here: auth is per-rpc on this service, not uniform across it.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import literature_pb2 as _literature_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class LiteratureStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> LiteratureAsyncStub: ...
    DescribePaper: _grpc.UnaryUnaryMultiCallable[_literature_pb2.DescribePaperRequest, _literature_pb2.PaperInfo]
    """What representations and files a paper offers; the pane's default-representation choice.
    An unknown doc_id is a NOT_FOUND the server adds.
    """
    ResolveContent: _grpc.UnaryUnaryMultiCallable[_literature_pb2.ResolveContentRequest, _literature_pb2.ContentLocation]
    """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
    doc_id or a selected object the paper lacks.
    """
    Locate: _grpc.UnaryUnaryMultiCallable[_literature_pb2.LocateRequest, _literature_pb2.LocateResponse]
    """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
    when the paper lacks the requested representation; a `not_located` result when the quote is
    absent (not an error).
    """
    Validate: _grpc.UnaryUnaryMultiCallable[_literature_pb2.ValidateRequest, _literature_pb2.ValidateResponse]
    """Whether a quote locates in any representation — the agent's authoring-time check."""
    PollFullTexts: _grpc.UnaryUnaryMultiCallable[_literature_pb2.PollFullTextsRequest, _literature_pb2.PollFullTextsResponse]
    """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
    effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
    sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
    anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
    whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
    sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
    serving slot for the whole wait.
    """
    MaybeIngestPapers: _grpc.UnaryUnaryMultiCallable[_literature_pb2.MaybeIngestPapersRequest, _literature_pb2.MaybeIngestPapersResponse]
    """Resolve external ids to papers, report each one's full-text readiness, and start production for
    the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
    not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
    unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
    Resolving ids against upstream sources litcache has never seen is the shape the name still grows
    into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

    Auth departs from the read rpcs because this one spends money: a call with a paper to produce
    resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
    themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
    on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

    A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
    outage affects the batch, and a caller reading it per-id would write papers off permanently.
    """

@_typing.type_check_only
class LiteratureAsyncStub(LiteratureStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribePaper: _aio.UnaryUnaryMultiCallable[_literature_pb2.DescribePaperRequest, _literature_pb2.PaperInfo]  # type: ignore[assignment]
    """What representations and files a paper offers; the pane's default-representation choice.
    An unknown doc_id is a NOT_FOUND the server adds.
    """
    ResolveContent: _aio.UnaryUnaryMultiCallable[_literature_pb2.ResolveContentRequest, _literature_pb2.ContentLocation]  # type: ignore[assignment]
    """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
    doc_id or a selected object the paper lacks.
    """
    Locate: _aio.UnaryUnaryMultiCallable[_literature_pb2.LocateRequest, _literature_pb2.LocateResponse]  # type: ignore[assignment]
    """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
    when the paper lacks the requested representation; a `not_located` result when the quote is
    absent (not an error).
    """
    Validate: _aio.UnaryUnaryMultiCallable[_literature_pb2.ValidateRequest, _literature_pb2.ValidateResponse]  # type: ignore[assignment]
    """Whether a quote locates in any representation — the agent's authoring-time check."""
    PollFullTexts: _aio.UnaryUnaryMultiCallable[_literature_pb2.PollFullTextsRequest, _literature_pb2.PollFullTextsResponse]  # type: ignore[assignment]
    """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
    effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
    sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
    anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
    whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
    sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
    serving slot for the whole wait.
    """
    MaybeIngestPapers: _aio.UnaryUnaryMultiCallable[_literature_pb2.MaybeIngestPapersRequest, _literature_pb2.MaybeIngestPapersResponse]  # type: ignore[assignment]
    """Resolve external ids to papers, report each one's full-text readiness, and start production for
    the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
    not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
    unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
    Resolving ids against upstream sources litcache has never seen is the shape the name still grows
    into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

    Auth departs from the read rpcs because this one spends money: a call with a paper to produce
    resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
    themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
    on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

    A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
    outage affects the batch, and a caller reading it per-id would write papers off permanently.
    """

class LiteratureServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def DescribePaper(
        self,
        request: _literature_pb2.DescribePaperRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.PaperInfo, _abc.Awaitable[_literature_pb2.PaperInfo]]:
        """What representations and files a paper offers; the pane's default-representation choice.
        An unknown doc_id is a NOT_FOUND the server adds.
        """

    @_abc_1.abstractmethod
    def ResolveContent(
        self,
        request: _literature_pb2.ResolveContentRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.ContentLocation, _abc.Awaitable[_literature_pb2.ContentLocation]]:
        """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
        doc_id or a selected object the paper lacks.
        """

    @_abc_1.abstractmethod
    def Locate(
        self,
        request: _literature_pb2.LocateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.LocateResponse, _abc.Awaitable[_literature_pb2.LocateResponse]]:
        """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
        when the paper lacks the requested representation; a `not_located` result when the quote is
        absent (not an error).
        """

    @_abc_1.abstractmethod
    def Validate(
        self,
        request: _literature_pb2.ValidateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.ValidateResponse, _abc.Awaitable[_literature_pb2.ValidateResponse]]:
        """Whether a quote locates in any representation — the agent's authoring-time check."""

    @_abc_1.abstractmethod
    def PollFullTexts(
        self,
        request: _literature_pb2.PollFullTextsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.PollFullTextsResponse, _abc.Awaitable[_literature_pb2.PollFullTextsResponse]]:
        """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
        effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
        sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
        anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
        whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
        sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
        serving slot for the whole wait.
        """

    @_abc_1.abstractmethod
    def MaybeIngestPapers(
        self,
        request: _literature_pb2.MaybeIngestPapersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.MaybeIngestPapersResponse, _abc.Awaitable[_literature_pb2.MaybeIngestPapersResponse]]:
        """Resolve external ids to papers, report each one's full-text readiness, and start production for
        the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
        not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
        unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
        Resolving ids against upstream sources litcache has never seen is the shape the name still grows
        into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

        Auth departs from the read rpcs because this one spends money: a call with a paper to produce
        resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
        themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
        on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

        A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
        outage affects the batch, and a caller reading it per-id would write papers off permanently.
        """

def add_LiteratureServicer_to_server(servicer: LiteratureServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
