# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import literature_pb2 as themis_dot_rpc_dot_literature__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/literature_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LiteratureStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribePaper = channel.unary_unary(
                '/themis.rpc.literature.Literature/DescribePaper',
                request_serializer=themis_dot_rpc_dot_literature__pb2.DescribePaperRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.PaperInfo.FromString,
                _registered_method=True)
        self.ResolveContent = channel.unary_unary(
                '/themis.rpc.literature.Literature/ResolveContent',
                request_serializer=themis_dot_rpc_dot_literature__pb2.ResolveContentRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.ContentLocation.FromString,
                _registered_method=True)
        self.Locate = channel.unary_unary(
                '/themis.rpc.literature.Literature/Locate',
                request_serializer=themis_dot_rpc_dot_literature__pb2.LocateRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.LocateResponse.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/themis.rpc.literature.Literature/Validate',
                request_serializer=themis_dot_rpc_dot_literature__pb2.ValidateRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.EnsureFullText = channel.unary_unary(
                '/themis.rpc.literature.Literature/EnsureFullText',
                request_serializer=themis_dot_rpc_dot_literature__pb2.EnsureFullTextRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.EnsureFullTextResponse.FromString,
                _registered_method=True)
        self.AwaitFullText = channel.unary_unary(
                '/themis.rpc.literature.Literature/AwaitFullText',
                request_serializer=themis_dot_rpc_dot_literature__pb2.AwaitFullTextRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_literature__pb2.AwaitFullTextResponse.FromString,
                _registered_method=True)


class LiteratureServicer:
    """Missing associated documentation comment in .proto file."""

    def DescribePaper(self, request, context):
        """What representations and files a paper offers; the pane's default-representation choice.
        An unknown doc_id is a NOT_FOUND the server adds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveContent(self, request, context):
        """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
        doc_id or a selected object the paper lacks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Locate(self, request, context):
        """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
        when the paper lacks the requested representation; a `not_located` result when the quote is
        absent (not an error).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Whether a quote locates in any representation — the agent's authoring-time check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureFullText(self, request, context):
        """Report each paper's full-text readiness (batch), derived from the litcache layout. A rendering
        present is READY; a paper whose source could yield one but has none is PENDING; a terminal
        sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
        an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a whole-batch abort). The caller works
        with the READY papers and polls the PENDING ids. Nothing produces a rendering on demand yet, so a
        PENDING id settles only once one is written.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitFullText(self, request, context):
        """Block until every requested paper has settled (no id PENDING) or the wait elapses, then report
        each id's readiness — the long-poll the caller uses to wait on PENDING ids without busy-polling.
        Same per-id readiness shape as EnsureFullText; an unset or negative timeout is INVALID_ARGUMENT,
        and one longer than the server ceiling is clamped, so a caller that must wait longer calls again.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiteratureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribePaper': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribePaper,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.DescribePaperRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.PaperInfo.SerializeToString,
            ),
            'ResolveContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveContent,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.ResolveContentRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.ContentLocation.SerializeToString,
            ),
            'Locate': grpc.unary_unary_rpc_method_handler(
                    servicer.Locate,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.LocateRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.LocateResponse.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.ValidateRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.ValidateResponse.SerializeToString,
            ),
            'EnsureFullText': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureFullText,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.EnsureFullTextRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.EnsureFullTextResponse.SerializeToString,
            ),
            'AwaitFullText': grpc.unary_unary_rpc_method_handler(
                    servicer.AwaitFullText,
                    request_deserializer=themis_dot_rpc_dot_literature__pb2.AwaitFullTextRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_literature__pb2.AwaitFullTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.literature.Literature', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.literature.Literature', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Literature:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DescribePaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/DescribePaper',
            themis_dot_rpc_dot_literature__pb2.DescribePaperRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.PaperInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/ResolveContent',
            themis_dot_rpc_dot_literature__pb2.ResolveContentRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.ContentLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Locate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/Locate',
            themis_dot_rpc_dot_literature__pb2.LocateRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.LocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/Validate',
            themis_dot_rpc_dot_literature__pb2.ValidateRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureFullText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/EnsureFullText',
            themis_dot_rpc_dot_literature__pb2.EnsureFullTextRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.EnsureFullTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwaitFullText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.literature.Literature/AwaitFullText',
            themis_dot_rpc_dot_literature__pb2.AwaitFullTextRequest.SerializeToString,
            themis_dot_rpc_dot_literature__pb2.AwaitFullTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
