"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `Literature` service — the literature evidence layer, in two groups. The store group owns
litcache resolution (docs/design/document-pane.md): given a canonical doc_id it names the GCS
object for a rendering, the PDF, or an associated file, serves the rendering's text, and locates a
citation's quote within a chosen representation (offsets in markdown; a page region in a PDF). The
discovery group reaches the live indexes — Europe PMC for keyword search, PubMed for the
bibliographic records behind a batch of PMIDs, NCBI's LitVar2 for the variant entity census — and
every outbound call is the service's own, since the agent holds no credential and no egress. This
proto is the source of truth; `regen` (buf generate) emits the themis/rpc/literature stubs — the
server subclasses the servicer base, a caller uses the stub.

Two callers reach this service: the web tier's backend, for the browser's paper display, and the
sandbox agent, which searches the indexes, resolves the identifiers it holds to doc_ids, reads the
markdown behind one, and validates a quote at authoring time. The corpus is shared across analyses
(entitlement is a deferred non-goal, literature-evidence-layer.md); which rpcs resolve a session,
and for what, each rpc states (docs/design/sandbox-rpc-exposure.md).
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import literature_pb2 as _literature_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class LiteratureStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> LiteratureAsyncStub: ...
    DescribePaper: _grpc.UnaryUnaryMultiCallable[_literature_pb2.DescribePaperRequest, _literature_pb2.PaperInfo]
    """What representations and files a paper offers; the pane's default-representation choice. The
    web tier's backend calls this for the browser's paper display, as it does ResolveContent and Locate.
    An unknown doc_id is a NOT_FOUND the server adds.
    """
    ResolveContent: _grpc.UnaryUnaryMultiCallable[_literature_pb2.ResolveContentRequest, _literature_pb2.ContentLocation]
    """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
    doc_id or a selected object the paper lacks.
    """
    Locate: _grpc.UnaryUnaryMultiCallable[_literature_pb2.LocateRequest, _literature_pb2.LocateResponse]
    """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
    when the paper lacks the requested representation; INTERNAL when the rendering it must read is
    listed but unreadable; a `not_located` result when the quote is absent (not an error). No
    producer resolves a quote against a PDF yet, so the live store answers a `REPRESENTATION_PDF`
    request UNIMPLEMENTED rather than the `not_located` that would read as the quote being absent
    from the paper. The fixture resolves its seeded PDF quotes, in the provisional coordinate
    space `Rect` states, so the pane's highlight path can be built offline.
    """
    Validate: _grpc.UnaryUnaryMultiCallable[_literature_pb2.ValidateRequest, _literature_pb2.ValidateResponse]
    """Whether a quote locates in any representation — the agent's authoring-time check. An unknown
    doc_id and an absent quote are both `ok=false` with a reason, not errors; INTERNAL when the
    rendering it must read is listed but unreadable, since a store fault reported `ok=false` would
    read as the quote failing to validate.
    """
    PollFullTexts: _grpc.UnaryUnaryMultiCallable[_literature_pb2.PollFullTextsRequest, _literature_pb2.PollFullTextsResponse]
    """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
    effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
    sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
    anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
    whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
    sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
    serving slot for the whole wait.
    """
    MaybeIngestPapers: _grpc.UnaryUnaryMultiCallable[_literature_pb2.MaybeIngestPapersRequest, _literature_pb2.MaybeIngestPapersResponse]
    """Resolve external ids to papers, report each one's full-text readiness, and start production for
    the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
    not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
    unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
    Resolving ids against upstream sources litcache has never seen is the shape the name still grows
    into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

    Auth departs from the read rpcs because this one spends money: a call with a paper to produce
    resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
    themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
    on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

    A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
    outage affects the batch, and a caller reading it per-id would write papers off permanently.
    """
    GetMarkdown: _grpc.UnaryUnaryMultiCallable[_literature_pb2.GetMarkdownRequest, _literature_pb2.GetMarkdownResponse]
    """The paper's canonical rendering as markdown — the agent's read path. NOT_FOUND for an unknown
    doc_id (a broken reference); INTERNAL for a rendering the manifest lists but the store cannot
    produce (the store broke its own invariant, not a fact about the paper); an `unavailable`
    result for a known paper with no rendering at all (a fact about the store, not an error).
    """
    SearchEuropePmc: _grpc.UnaryUnaryMultiCallable[_literature_pb2.SearchEuropePmcRequest, _literature_pb2.SearchEuropePmcResponse]
    """Search the live Europe PMC index by keyword and return matching bibliographic records. The
    records are the index's, not the store's: a hit here says a paper exists, never that its text
    is readable — `MaybeIngestPapers` is what says that. `total_matched` says how much of the
    index's match the returned records cover; see `SearchEuropePmcResponse`.
    """
    FetchPubmedArticles: _grpc.UnaryUnaryMultiCallable[_literature_pb2.FetchPubmedArticlesRequest, _literature_pb2.FetchPubmedArticlesResponse]
    """Fetch the PubMed record — abstract included — for each of a batch of PMIDs. The route from an
    identifier to something readable where the store holds no full text: an abstract is often enough
    to judge whether the work matters, and for a conference abstract it is the whole of what was
    published. Answers with PubMed's own record whole, in the kind PubMed indexes the PMID under —
    `pubmed.PubmedArticle` for a journal record, `pubmed.PubmedBookArticle` for a book record — the
    record the store embeds in a paper's canonical metadata. It produces and ingests nothing —
    `MaybeIngestPapers` is the one door into the full-text store. INVALID_ARGUMENT for a malformed,
    empty or oversized batch.
    """
    SearchLitVar: _grpc.UnaryUnaryMultiCallable[_literature_pb2.SearchLitVarRequest, _literature_pb2.SearchLitVarResponse]
    """Resolve a variant through LitVar2 and return every entity it reached, unmerged and labelled.
    The index splits one variant across entities that share no record, so the answer is a candidate
    set, not a list: each carries the index's own labels, an `agreement` verdict per identifier, its
    whole record count, and its top-ranked PMIDs up to the `max_pmids_per_entity` budget.
    Choosing among them, deduplicating a PMID that reaches several, and reading any of them through
    `FetchPubmedArticles`, is the caller's. `entity_id` re-asks for one entity; `total_entities`
    above `entities.size()` says the fan-out ceiling left candidates unexamined. See
    `SearchLitVarResponse`.
    """
    ListLitVarEntities: _grpc.UnaryUnaryMultiCallable[_literature_pb2.ListLitVarEntitiesRequest, _literature_pb2.ListLitVarEntitiesResponse]
    """List the variant entities LitVar2 holds for a gene, most-published first, narrowed by `contains`
    on the entity id. The route to an entity indexed under a name no current identifier constructs —
    a superseded numbering, say — whose id then goes back through `SearchLitVar.entity_id` to list
    its PMIDs. See `ListLitVarEntitiesResponse`.
    """

@_typing.type_check_only
class LiteratureAsyncStub(LiteratureStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribePaper: _aio.UnaryUnaryMultiCallable[_literature_pb2.DescribePaperRequest, _literature_pb2.PaperInfo]  # type: ignore[assignment]
    """What representations and files a paper offers; the pane's default-representation choice. The
    web tier's backend calls this for the browser's paper display, as it does ResolveContent and Locate.
    An unknown doc_id is a NOT_FOUND the server adds.
    """
    ResolveContent: _aio.UnaryUnaryMultiCallable[_literature_pb2.ResolveContentRequest, _literature_pb2.ContentLocation]  # type: ignore[assignment]
    """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
    doc_id or a selected object the paper lacks.
    """
    Locate: _aio.UnaryUnaryMultiCallable[_literature_pb2.LocateRequest, _literature_pb2.LocateResponse]  # type: ignore[assignment]
    """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
    when the paper lacks the requested representation; INTERNAL when the rendering it must read is
    listed but unreadable; a `not_located` result when the quote is absent (not an error). No
    producer resolves a quote against a PDF yet, so the live store answers a `REPRESENTATION_PDF`
    request UNIMPLEMENTED rather than the `not_located` that would read as the quote being absent
    from the paper. The fixture resolves its seeded PDF quotes, in the provisional coordinate
    space `Rect` states, so the pane's highlight path can be built offline.
    """
    Validate: _aio.UnaryUnaryMultiCallable[_literature_pb2.ValidateRequest, _literature_pb2.ValidateResponse]  # type: ignore[assignment]
    """Whether a quote locates in any representation — the agent's authoring-time check. An unknown
    doc_id and an absent quote are both `ok=false` with a reason, not errors; INTERNAL when the
    rendering it must read is listed but unreadable, since a store fault reported `ok=false` would
    read as the quote failing to validate.
    """
    PollFullTexts: _aio.UnaryUnaryMultiCallable[_literature_pb2.PollFullTextsRequest, _literature_pb2.PollFullTextsResponse]  # type: ignore[assignment]
    """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
    effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
    sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
    anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
    whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
    sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
    serving slot for the whole wait.
    """
    MaybeIngestPapers: _aio.UnaryUnaryMultiCallable[_literature_pb2.MaybeIngestPapersRequest, _literature_pb2.MaybeIngestPapersResponse]  # type: ignore[assignment]
    """Resolve external ids to papers, report each one's full-text readiness, and start production for
    the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
    not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
    unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
    Resolving ids against upstream sources litcache has never seen is the shape the name still grows
    into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

    Auth departs from the read rpcs because this one spends money: a call with a paper to produce
    resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
    themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
    on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

    A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
    outage affects the batch, and a caller reading it per-id would write papers off permanently.
    """
    GetMarkdown: _aio.UnaryUnaryMultiCallable[_literature_pb2.GetMarkdownRequest, _literature_pb2.GetMarkdownResponse]  # type: ignore[assignment]
    """The paper's canonical rendering as markdown — the agent's read path. NOT_FOUND for an unknown
    doc_id (a broken reference); INTERNAL for a rendering the manifest lists but the store cannot
    produce (the store broke its own invariant, not a fact about the paper); an `unavailable`
    result for a known paper with no rendering at all (a fact about the store, not an error).
    """
    SearchEuropePmc: _aio.UnaryUnaryMultiCallable[_literature_pb2.SearchEuropePmcRequest, _literature_pb2.SearchEuropePmcResponse]  # type: ignore[assignment]
    """Search the live Europe PMC index by keyword and return matching bibliographic records. The
    records are the index's, not the store's: a hit here says a paper exists, never that its text
    is readable — `MaybeIngestPapers` is what says that. `total_matched` says how much of the
    index's match the returned records cover; see `SearchEuropePmcResponse`.
    """
    FetchPubmedArticles: _aio.UnaryUnaryMultiCallable[_literature_pb2.FetchPubmedArticlesRequest, _literature_pb2.FetchPubmedArticlesResponse]  # type: ignore[assignment]
    """Fetch the PubMed record — abstract included — for each of a batch of PMIDs. The route from an
    identifier to something readable where the store holds no full text: an abstract is often enough
    to judge whether the work matters, and for a conference abstract it is the whole of what was
    published. Answers with PubMed's own record whole, in the kind PubMed indexes the PMID under —
    `pubmed.PubmedArticle` for a journal record, `pubmed.PubmedBookArticle` for a book record — the
    record the store embeds in a paper's canonical metadata. It produces and ingests nothing —
    `MaybeIngestPapers` is the one door into the full-text store. INVALID_ARGUMENT for a malformed,
    empty or oversized batch.
    """
    SearchLitVar: _aio.UnaryUnaryMultiCallable[_literature_pb2.SearchLitVarRequest, _literature_pb2.SearchLitVarResponse]  # type: ignore[assignment]
    """Resolve a variant through LitVar2 and return every entity it reached, unmerged and labelled.
    The index splits one variant across entities that share no record, so the answer is a candidate
    set, not a list: each carries the index's own labels, an `agreement` verdict per identifier, its
    whole record count, and its top-ranked PMIDs up to the `max_pmids_per_entity` budget.
    Choosing among them, deduplicating a PMID that reaches several, and reading any of them through
    `FetchPubmedArticles`, is the caller's. `entity_id` re-asks for one entity; `total_entities`
    above `entities.size()` says the fan-out ceiling left candidates unexamined. See
    `SearchLitVarResponse`.
    """
    ListLitVarEntities: _aio.UnaryUnaryMultiCallable[_literature_pb2.ListLitVarEntitiesRequest, _literature_pb2.ListLitVarEntitiesResponse]  # type: ignore[assignment]
    """List the variant entities LitVar2 holds for a gene, most-published first, narrowed by `contains`
    on the entity id. The route to an entity indexed under a name no current identifier constructs —
    a superseded numbering, say — whose id then goes back through `SearchLitVar.entity_id` to list
    its PMIDs. See `ListLitVarEntitiesResponse`.
    """

class LiteratureServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def DescribePaper(
        self,
        request: _literature_pb2.DescribePaperRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.PaperInfo, _abc.Awaitable[_literature_pb2.PaperInfo]]:
        """What representations and files a paper offers; the pane's default-representation choice. The
        web tier's backend calls this for the browser's paper display, as it does ResolveContent and Locate.
        An unknown doc_id is a NOT_FOUND the server adds.
        """

    @_abc_1.abstractmethod
    def ResolveContent(
        self,
        request: _literature_pb2.ResolveContentRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.ContentLocation, _abc.Awaitable[_literature_pb2.ContentLocation]]:
        """Name the GCS object for a rendering, the PDF, or an associated file. NOT_FOUND for an unknown
        doc_id or a selected object the paper lacks.
        """

    @_abc_1.abstractmethod
    def Locate(
        self,
        request: _literature_pb2.LocateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.LocateResponse, _abc.Awaitable[_literature_pb2.LocateResponse]]:
        """Locate a quote within a representation. NOT_FOUND for an unknown doc_id; FAILED_PRECONDITION
        when the paper lacks the requested representation; INTERNAL when the rendering it must read is
        listed but unreadable; a `not_located` result when the quote is absent (not an error). No
        producer resolves a quote against a PDF yet, so the live store answers a `REPRESENTATION_PDF`
        request UNIMPLEMENTED rather than the `not_located` that would read as the quote being absent
        from the paper. The fixture resolves its seeded PDF quotes, in the provisional coordinate
        space `Rect` states, so the pane's highlight path can be built offline.
        """

    @_abc_1.abstractmethod
    def Validate(
        self,
        request: _literature_pb2.ValidateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.ValidateResponse, _abc.Awaitable[_literature_pb2.ValidateResponse]]:
        """Whether a quote locates in any representation — the agent's authoring-time check. An unknown
        doc_id and an absent quote are both `ok=false` with a reason, not errors; INTERNAL when the
        rendering it must read is listed but unreadable, since a store fault reported `ok=false` would
        read as the quote failing to validate.
        """

    @_abc_1.abstractmethod
    def PollFullTexts(
        self,
        request: _literature_pb2.PollFullTextsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.PollFullTextsResponse, _abc.Awaitable[_literature_pb2.PollFullTextsResponse]]:
        """Report each paper's full-text readiness (batch), derived from the litcache layout, with no side
        effect — it produces nothing and enqueues nothing. A rendering present is READY; a terminal
        sidecar is NO_FULL_TEXT (nothing served it) or FAILED (a conversion will not succeed on retry);
        anything else is PENDING; an unknown doc_id is UNKNOWN_PAPER (a per-id result, never a
        whole-batch abort). Blocking server-side is deliberately not offered: a caller with somewhere to
        sleep (a sandbox, a browser) waits there for one round trip, where a held request would occupy a
        serving slot for the whole wait.
        """

    @_abc_1.abstractmethod
    def MaybeIngestPapers(
        self,
        request: _literature_pb2.MaybeIngestPapersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.MaybeIngestPapersResponse, _abc.Awaitable[_literature_pb2.MaybeIngestPapersResponse]]:
        """Resolve external ids to papers, report each one's full-text readiness, and start production for
        the papers that need it. An id litcache has already ingested resolves to its doc_id; one it has
        not comes back with an empty doc_id and UNKNOWN_PAPER. It never mints — a mint claims, so an
        unknown id would take a doc_id that names no manifest and a crosswalk claim on that DOI.
        Resolving ids against upstream sources litcache has never seen is the shape the name still grows
        into. `Maybe` is load-bearing either way — a call may resolve nothing and produce nothing.

        Auth departs from the read rpcs because this one spends money: a call with a paper to produce
        resolves a session first — the token arrives as x-themis-session-token metadata and resolves via
        themis.clients.auth, never as a message field. UNAUTHENTICATED with no token, PERMISSION_DENIED
        on one that does not resolve. A call whose ids are all settled produces nothing and needs none.

        A crosswalk that cannot be reached is UNAVAILABLE for the whole call, never a per-id miss: an
        outage affects the batch, and a caller reading it per-id would write papers off permanently.
        """

    @_abc_1.abstractmethod
    def GetMarkdown(
        self,
        request: _literature_pb2.GetMarkdownRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.GetMarkdownResponse, _abc.Awaitable[_literature_pb2.GetMarkdownResponse]]:
        """The paper's canonical rendering as markdown — the agent's read path. NOT_FOUND for an unknown
        doc_id (a broken reference); INTERNAL for a rendering the manifest lists but the store cannot
        produce (the store broke its own invariant, not a fact about the paper); an `unavailable`
        result for a known paper with no rendering at all (a fact about the store, not an error).
        """

    @_abc_1.abstractmethod
    def SearchEuropePmc(
        self,
        request: _literature_pb2.SearchEuropePmcRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.SearchEuropePmcResponse, _abc.Awaitable[_literature_pb2.SearchEuropePmcResponse]]:
        """Search the live Europe PMC index by keyword and return matching bibliographic records. The
        records are the index's, not the store's: a hit here says a paper exists, never that its text
        is readable — `MaybeIngestPapers` is what says that. `total_matched` says how much of the
        index's match the returned records cover; see `SearchEuropePmcResponse`.
        """

    @_abc_1.abstractmethod
    def FetchPubmedArticles(
        self,
        request: _literature_pb2.FetchPubmedArticlesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.FetchPubmedArticlesResponse, _abc.Awaitable[_literature_pb2.FetchPubmedArticlesResponse]]:
        """Fetch the PubMed record — abstract included — for each of a batch of PMIDs. The route from an
        identifier to something readable where the store holds no full text: an abstract is often enough
        to judge whether the work matters, and for a conference abstract it is the whole of what was
        published. Answers with PubMed's own record whole, in the kind PubMed indexes the PMID under —
        `pubmed.PubmedArticle` for a journal record, `pubmed.PubmedBookArticle` for a book record — the
        record the store embeds in a paper's canonical metadata. It produces and ingests nothing —
        `MaybeIngestPapers` is the one door into the full-text store. INVALID_ARGUMENT for a malformed,
        empty or oversized batch.
        """

    @_abc_1.abstractmethod
    def SearchLitVar(
        self,
        request: _literature_pb2.SearchLitVarRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.SearchLitVarResponse, _abc.Awaitable[_literature_pb2.SearchLitVarResponse]]:
        """Resolve a variant through LitVar2 and return every entity it reached, unmerged and labelled.
        The index splits one variant across entities that share no record, so the answer is a candidate
        set, not a list: each carries the index's own labels, an `agreement` verdict per identifier, its
        whole record count, and its top-ranked PMIDs up to the `max_pmids_per_entity` budget.
        Choosing among them, deduplicating a PMID that reaches several, and reading any of them through
        `FetchPubmedArticles`, is the caller's. `entity_id` re-asks for one entity; `total_entities`
        above `entities.size()` says the fan-out ceiling left candidates unexamined. See
        `SearchLitVarResponse`.
        """

    @_abc_1.abstractmethod
    def ListLitVarEntities(
        self,
        request: _literature_pb2.ListLitVarEntitiesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_literature_pb2.ListLitVarEntitiesResponse, _abc.Awaitable[_literature_pb2.ListLitVarEntitiesResponse]]:
        """List the variant entities LitVar2 holds for a gene, most-published first, narrowed by `contains`
        on the entity id. The route to an entity indexed under a name no current identifier constructs —
        a superseded numbering, say — whose id then goes back through `SearchLitVar.entity_id` to list
        its PMIDs. See `ListLitVarEntitiesResponse`.
        """

def add_LiteratureServicer_to_server(servicer: LiteratureServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
