"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
mavedb: MaveDB — the depositor's calibrated multiplexed-assay result for one variant, the *_FXN
input. Design: docs/design/evidence-interfaces.md.

Modelled from:
  MaveDB API (mapped variants by ClinGen allele id, and the score set behind a row):
    `DescribeVariantResponse` carries the depositor's Brnich calibration fields — `oddspath_ratio`,
    `acmg_criterion`, `acmg_strength`, `score` — under MaveDB's names; `raw` is the score-set row.
  This interface's own design: `DescribeVariantRequest` — the HGVS the service registers a ClinGen
    allele under, since MaveDB holds no HGVS-keyed lookup.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import mavedb_pb2 as _mavedb_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MaveDbStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MaveDbAsyncStub: ...
    DescribeVariant: _grpc.UnaryUnaryMultiCallable[_mavedb_pb2.DescribeVariantRequest, _mavedb_pb2.DescribeVariantResponse]
    """MaveDB, keyed on the variant's ClinGen allele (ClinGen Allele Registry): reads the
    depositor's OddsPath calibration for the assayed row's score (when one was deposited) -> *_FXN.
    See DescribeVariantResponse.
    """

@_typing.type_check_only
class MaveDbAsyncStub(MaveDbStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribeVariant: _aio.UnaryUnaryMultiCallable[_mavedb_pb2.DescribeVariantRequest, _mavedb_pb2.DescribeVariantResponse]  # type: ignore[assignment]
    """MaveDB, keyed on the variant's ClinGen allele (ClinGen Allele Registry): reads the
    depositor's OddsPath calibration for the assayed row's score (when one was deposited) -> *_FXN.
    See DescribeVariantResponse.
    """

class MaveDbServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def DescribeVariant(
        self,
        request: _mavedb_pb2.DescribeVariantRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mavedb_pb2.DescribeVariantResponse, _abc.Awaitable[_mavedb_pb2.DescribeVariantResponse]]:
        """MaveDB, keyed on the variant's ClinGen allele (ClinGen Allele Registry): reads the
        depositor's OddsPath calibration for the assayed row's score (when one was deposited) -> *_FXN.
        See DescribeVariantResponse.
        """

def add_MaveDbServicer_to_server(servicer: MaveDbServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
