"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `sheaf` service: a repository's mutable state and packs, behind the one credential on
sheaf's bucket (docs/design/sheaf.md). This proto is the source of truth; `regen` (buf generate) emits the
themis/rpc/sheaf stubs each consumer imports.

Sheaf is git over object storage: content-addressed packfiles plus one ref document replaced by
compare-and-swap. The service holds the bucket and runs sheaf's storage protocol; a caller holds
the objects. The first caller is the sandbox worker: its bare mirror hydrates through ReadRefDoc and
FetchPack, and its pre-receive hook publishes through Publish. The guest's git sees none of this —
it speaks git's own protocol to the worker's mirror over the stream hatch, and the mirror is where
git's world ends and sheaf's begins. The curator's browser is the second caller: it keeps a copy
of the repository of its own, hydrated through ReadRefDoc and the packs SignPackUrls signs download
URLs for, and publishes a curator's commit through Publish. The BFF relays each of those calls as
the web tier, naming the Analysis through a session it derives for it
(docs/design/workbench-workspace.md). Every call here is scoped to one repository by the session
it names (resolved to an Analysis; the repository is that Analysis's), so no request names a
repository and a caller can reach only its own.

The split of checks follows what each side holds. The service refuses what it can decide from
the document alone: a name or id git cannot hold, a ref set git cannot store, a deletion, a
publish that moves a ref without advancing the reflog ref, and a base the document has moved
past. What needs the objects — that a move is a fast-forward, that the reflog entry's parents are
the tips it records — is the caller's contract, as it is for every sheaf writer.

Publish only extends the pack manifest. Compaction's write — a pack set that replaces the manifest
— has no rpc here because nothing runs compaction yet (docs/design/sheaf.md, Open questions); when
something does, it gains a ReplacePacks rpc beside these, an additive change.
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from themis.rpc import sheaf_pb2 as _sheaf_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SheafStub:
    """A sheaf repository's storage protocol, served for the repository the session names."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SheafAsyncStub: ...
    ReadRefDoc: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _sheaf_pb2.RefDocSnapshot]
    """The current ref document and its generation; an unset document is a repository that does not
    exist yet, not an error. DATA_LOSS if the stored document does not parse as one this code
    wrote: that is damage, and a caller must not retry it as a fault.
    """
    FetchPack: _grpc.UnaryStreamMultiCallable[_sheaf_pb2.FetchPackRequest, _sheaf_pb2.PackChunk]
    """One packfile the document names, streamed. INVALID_ARGUMENT if `pack_id` is not sixty-four hex
    digits; NOT_FOUND if no such pack: nothing in a sheaf store is ever deleted, so that is a fact
    about the caller's request, never about timing.
    """
    Publish: _grpc.StreamUnaryMultiCallable[_sheaf_pb2.PublishRequest, _sheaf_pb2.PublishResponse]
    """Upload packs and replace the ref document in one operation, conditional on the base
    generation. Packs land before the document names them, so a refusal leaves at most inert
    litter and never a ref nothing can fetch. A moved document is classified as `base_generation`
    describes: a publish that already landed succeeds again, so a lost response is recovered by
    retrying. Refusals: ABORTED when the document moved and every ref the intent moves outside
    `refs/sheaf/` is as the caller read it (rebuild, publish again). FAILED_PRECONDITION when the
    document moved and one of those refs moved with it (a non-fast-forward, for the caller to
    merge). INVALID_ARGUMENT for a
    name or id git cannot hold (the zero id included), a ref set it cannot store, a deletion, an
    intent moving no ref outside `refs/sheaf/`, a HEAD naming neither an object nor a ref, a
    publish that forgets the reflog ref, a declared pack id that is not sixty-four hex digits, a
    pack whose bytes do not match its declared size or hash, or a malformed stream — no intent, an intent after a chunk, a pack index out of order or beyond
    the declared list.
    RESOURCE_EXHAUSTED when the declared packs exceed the deployment's per-publish byte ceiling, or
    the ref set the publish would leave exceeds its ref-count or document-size ceiling — both
    decided from the intent and the current document before any pack is stored. The ref set only
    grows, since nothing is deleted, so it is bounded for the same reason the bytes are. DATA_LOSS
    when the stored document does not parse as one this code wrote: damage, which a caller must not
    retry. Faults, not refusals, are gRPC's ordinary codes: UNAVAILABLE or INTERNAL for a storage
    fault a caller retries.
    """
    SignPackUrls: _grpc.UnaryUnaryMultiCallable[_sheaf_pb2.SignPackUrlsRequest, _sheaf_pb2.SignPackUrlsResponse]
    """Signed download URLs, with sizes, for packs the current document lists, so a caller that keeps
    its own copy of the repository downloads them from the bucket instead of streaming them through
    this service. The signing happens here because a signed URL carries the signer's own read
    permission, and this service is the one identity with a role on the bucket. Refusals as
    SignPackUrlsRequest states. DATA_LOSS when the document lists a pack the store does not hold, or
    the stored document does not parse as one this code wrote: damage, which a caller must not retry.
    UNIMPLEMENTED when the deployment's storage backend cannot sign, as the local-directory backend
    cannot.
    """

@_typing.type_check_only
class SheafAsyncStub(SheafStub):
    """A sheaf repository's storage protocol, served for the repository the session names."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    ReadRefDoc: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _sheaf_pb2.RefDocSnapshot]  # type: ignore[assignment]
    """The current ref document and its generation; an unset document is a repository that does not
    exist yet, not an error. DATA_LOSS if the stored document does not parse as one this code
    wrote: that is damage, and a caller must not retry it as a fault.
    """
    FetchPack: _aio.UnaryStreamMultiCallable[_sheaf_pb2.FetchPackRequest, _sheaf_pb2.PackChunk]  # type: ignore[assignment]
    """One packfile the document names, streamed. INVALID_ARGUMENT if `pack_id` is not sixty-four hex
    digits; NOT_FOUND if no such pack: nothing in a sheaf store is ever deleted, so that is a fact
    about the caller's request, never about timing.
    """
    Publish: _aio.StreamUnaryMultiCallable[_sheaf_pb2.PublishRequest, _sheaf_pb2.PublishResponse]  # type: ignore[assignment]
    """Upload packs and replace the ref document in one operation, conditional on the base
    generation. Packs land before the document names them, so a refusal leaves at most inert
    litter and never a ref nothing can fetch. A moved document is classified as `base_generation`
    describes: a publish that already landed succeeds again, so a lost response is recovered by
    retrying. Refusals: ABORTED when the document moved and every ref the intent moves outside
    `refs/sheaf/` is as the caller read it (rebuild, publish again). FAILED_PRECONDITION when the
    document moved and one of those refs moved with it (a non-fast-forward, for the caller to
    merge). INVALID_ARGUMENT for a
    name or id git cannot hold (the zero id included), a ref set it cannot store, a deletion, an
    intent moving no ref outside `refs/sheaf/`, a HEAD naming neither an object nor a ref, a
    publish that forgets the reflog ref, a declared pack id that is not sixty-four hex digits, a
    pack whose bytes do not match its declared size or hash, or a malformed stream — no intent, an intent after a chunk, a pack index out of order or beyond
    the declared list.
    RESOURCE_EXHAUSTED when the declared packs exceed the deployment's per-publish byte ceiling, or
    the ref set the publish would leave exceeds its ref-count or document-size ceiling — both
    decided from the intent and the current document before any pack is stored. The ref set only
    grows, since nothing is deleted, so it is bounded for the same reason the bytes are. DATA_LOSS
    when the stored document does not parse as one this code wrote: damage, which a caller must not
    retry. Faults, not refusals, are gRPC's ordinary codes: UNAVAILABLE or INTERNAL for a storage
    fault a caller retries.
    """
    SignPackUrls: _aio.UnaryUnaryMultiCallable[_sheaf_pb2.SignPackUrlsRequest, _sheaf_pb2.SignPackUrlsResponse]  # type: ignore[assignment]
    """Signed download URLs, with sizes, for packs the current document lists, so a caller that keeps
    its own copy of the repository downloads them from the bucket instead of streaming them through
    this service. The signing happens here because a signed URL carries the signer's own read
    permission, and this service is the one identity with a role on the bucket. Refusals as
    SignPackUrlsRequest states. DATA_LOSS when the document lists a pack the store does not hold, or
    the stored document does not parse as one this code wrote: damage, which a caller must not retry.
    UNIMPLEMENTED when the deployment's storage backend cannot sign, as the local-directory backend
    cannot.
    """

class SheafServicer(metaclass=_abc_1.ABCMeta):
    """A sheaf repository's storage protocol, served for the repository the session names."""

    @_abc_1.abstractmethod
    def ReadRefDoc(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_sheaf_pb2.RefDocSnapshot, _abc.Awaitable[_sheaf_pb2.RefDocSnapshot]]:
        """The current ref document and its generation; an unset document is a repository that does not
        exist yet, not an error. DATA_LOSS if the stored document does not parse as one this code
        wrote: that is damage, and a caller must not retry it as a fault.
        """

    @_abc_1.abstractmethod
    def FetchPack(
        self,
        request: _sheaf_pb2.FetchPackRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_sheaf_pb2.PackChunk], _abc.AsyncIterator[_sheaf_pb2.PackChunk]]:
        """One packfile the document names, streamed. INVALID_ARGUMENT if `pack_id` is not sixty-four hex
        digits; NOT_FOUND if no such pack: nothing in a sheaf store is ever deleted, so that is a fact
        about the caller's request, never about timing.
        """

    @_abc_1.abstractmethod
    def Publish(
        self,
        request_iterator: _MaybeAsyncIterator[_sheaf_pb2.PublishRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_sheaf_pb2.PublishResponse, _abc.Awaitable[_sheaf_pb2.PublishResponse]]:
        """Upload packs and replace the ref document in one operation, conditional on the base
        generation. Packs land before the document names them, so a refusal leaves at most inert
        litter and never a ref nothing can fetch. A moved document is classified as `base_generation`
        describes: a publish that already landed succeeds again, so a lost response is recovered by
        retrying. Refusals: ABORTED when the document moved and every ref the intent moves outside
        `refs/sheaf/` is as the caller read it (rebuild, publish again). FAILED_PRECONDITION when the
        document moved and one of those refs moved with it (a non-fast-forward, for the caller to
        merge). INVALID_ARGUMENT for a
        name or id git cannot hold (the zero id included), a ref set it cannot store, a deletion, an
        intent moving no ref outside `refs/sheaf/`, a HEAD naming neither an object nor a ref, a
        publish that forgets the reflog ref, a declared pack id that is not sixty-four hex digits, a
        pack whose bytes do not match its declared size or hash, or a malformed stream — no intent, an intent after a chunk, a pack index out of order or beyond
        the declared list.
        RESOURCE_EXHAUSTED when the declared packs exceed the deployment's per-publish byte ceiling, or
        the ref set the publish would leave exceeds its ref-count or document-size ceiling — both
        decided from the intent and the current document before any pack is stored. The ref set only
        grows, since nothing is deleted, so it is bounded for the same reason the bytes are. DATA_LOSS
        when the stored document does not parse as one this code wrote: damage, which a caller must not
        retry. Faults, not refusals, are gRPC's ordinary codes: UNAVAILABLE or INTERNAL for a storage
        fault a caller retries.
        """

    @_abc_1.abstractmethod
    def SignPackUrls(
        self,
        request: _sheaf_pb2.SignPackUrlsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sheaf_pb2.SignPackUrlsResponse, _abc.Awaitable[_sheaf_pb2.SignPackUrlsResponse]]:
        """Signed download URLs, with sizes, for packs the current document lists, so a caller that keeps
        its own copy of the repository downloads them from the bucket instead of streaming them through
        this service. The signing happens here because a signed URL carries the signer's own read
        permission, and this service is the one identity with a role on the bucket. Refusals as
        SignPackUrlsRequest states. DATA_LOSS when the document lists a pack the store does not hold, or
        the stored document does not parse as one this code wrote: damage, which a caller must not retry.
        UNIMPLEMENTED when the deployment's storage backend cannot sign, as the local-directory backend
        cannot.
        """

def add_SheafServicer_to_server(servicer: SheafServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
