# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from themis.rpc import sheaf_pb2 as themis_dot_rpc_dot_sheaf__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/sheaf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SheafStub:
    """A sheaf repository's storage protocol, served for the repository the session names.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadRefDoc = channel.unary_unary(
                '/themis.rpc.sheaf.Sheaf/ReadRefDoc',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_sheaf__pb2.RefDocSnapshot.FromString,
                _registered_method=True)
        self.FetchPack = channel.unary_stream(
                '/themis.rpc.sheaf.Sheaf/FetchPack',
                request_serializer=themis_dot_rpc_dot_sheaf__pb2.FetchPackRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_sheaf__pb2.PackChunk.FromString,
                _registered_method=True)
        self.Publish = channel.stream_unary(
                '/themis.rpc.sheaf.Sheaf/Publish',
                request_serializer=themis_dot_rpc_dot_sheaf__pb2.PublishRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_sheaf__pb2.PublishResponse.FromString,
                _registered_method=True)


class SheafServicer:
    """A sheaf repository's storage protocol, served for the repository the session names.
    """

    def ReadRefDoc(self, request, context):
        """The current ref document and its generation; an unset document is a repository that does not
        exist yet, not an error. DATA_LOSS if the stored document does not parse as one this code
        wrote: that is damage, and a caller must not retry it as a fault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchPack(self, request, context):
        """One packfile the document names, streamed. INVALID_ARGUMENT if `pack_id` is not sixty-four hex
        digits; NOT_FOUND if no such pack: nothing in a sheaf store is ever deleted, so that is a fact
        about the caller's request, never about timing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request_iterator, context):
        """Upload packs and replace the ref document in one operation, conditional on the base
        generation. Packs land before the document names them, so a refusal leaves at most inert
        litter and never a ref nothing can fetch. A moved document is classified as `base_generation`
        describes: a publish that already landed succeeds again, so a lost response is recovered by
        retrying. Refusals: ABORTED when the document moved and every ref the intent moves outside
        `refs/sheaf/` is as the caller read it (rebuild, publish again). FAILED_PRECONDITION when the
        document moved and one of those refs moved with it (a non-fast-forward, for the caller to
        merge). INVALID_ARGUMENT for a
        name or id git cannot hold (the zero id included), a ref set it cannot store, a deletion, an
        intent moving no ref outside `refs/sheaf/`, a HEAD naming neither an object nor a ref, a
        publish that forgets the reflog ref, a declared pack id that is not sixty-four hex digits, a
        pack whose bytes do not match its declared size or hash, or a malformed stream — no intent, an intent after a chunk, a pack index out of order or beyond
        the declared list.
        RESOURCE_EXHAUSTED when the declared packs exceed the deployment's per-publish byte ceiling, or
        the ref set the publish would leave exceeds its ref-count or document-size ceiling — both
        decided from the intent and the current document before any pack is stored. The ref set only
        grows, since nothing is deleted, so it is bounded for the same reason the bytes are. Faults, not
        refusals, are gRPC's ordinary codes: UNAVAILABLE or INTERNAL for a storage fault a caller
        retries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SheafServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadRefDoc': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRefDoc,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=themis_dot_rpc_dot_sheaf__pb2.RefDocSnapshot.SerializeToString,
            ),
            'FetchPack': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchPack,
                    request_deserializer=themis_dot_rpc_dot_sheaf__pb2.FetchPackRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_sheaf__pb2.PackChunk.SerializeToString,
            ),
            'Publish': grpc.stream_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=themis_dot_rpc_dot_sheaf__pb2.PublishRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_sheaf__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.sheaf.Sheaf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.sheaf.Sheaf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sheaf:
    """A sheaf repository's storage protocol, served for the repository the session names.
    """

    @staticmethod
    def ReadRefDoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.sheaf.Sheaf/ReadRefDoc',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            themis_dot_rpc_dot_sheaf__pb2.RefDocSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/themis.rpc.sheaf.Sheaf/FetchPack',
            themis_dot_rpc_dot_sheaf__pb2.FetchPackRequest.SerializeToString,
            themis_dot_rpc_dot_sheaf__pb2.PackChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/themis.rpc.sheaf.Sheaf/Publish',
            themis_dot_rpc_dot_sheaf__pb2.PublishRequest.SerializeToString,
            themis_dot_rpc_dot_sheaf__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
