"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
splice: whether a splice site is lost (SpliceAI + Pangolin deltas), and what the transcript
becomes when one is. Design: docs/design/evidence-interfaces.md.

Modelled from:
  Broad SpliceAI + Pangolin lookup service: `PredictDeltasResponse.raw` carries both hosts'
    per-position deltas; the four typed scalars are those deltas reduced onto one orientation.
  SVCv4 SM8 (NMD, the 50-nt rule) and SM16 (NSD / stop-lost): `SpliceProduct`, and
    `PredictedSkip.nmd_predicted` / `nt_upstream_of_last_junction`, model the null-vs-coding fork
    the workflows route on.
  This interface's own design: both request messages, `PredictedSkip` and
    `PredictSkipOutcomeResponse` — the skipped transcript is composed here from VariantValidator's
    exon table and NCBI Nucleotide's sequence, and no upstream returns it.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import splice_pb2 as _splice_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SpliceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SpliceAsyncStub: ...
    PredictDeltas: _grpc.UnaryUnaryMultiCallable[_splice_pb2.PredictDeltasRequest, _splice_pb2.PredictDeltasResponse]
    """Broad SpliceAI + Pangolin: each predictor's per-transcript deltas reduced to one gain and
    one loss on a shared orientation -> SPL_PRD input; the product-consequence call is the model's
    (SM11/SM18). See PredictDeltasResponse.
    """
    PredictSkipOutcome: _grpc.UnaryUnaryMultiCallable[_splice_pb2.PredictSkipOutcomeRequest, _splice_pb2.PredictSkipOutcomeResponse]
    """The exon table (VariantValidator) + the RefSeq transcript sequence (NCBI Nucleotide): given a
    lost splice site, the skipped transcript's frame, PTC and NMD prediction — NOT whether the site
    is lost (that is PredictDeltas). See PredictSkipOutcomeResponse.
    """

@_typing.type_check_only
class SpliceAsyncStub(SpliceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    PredictDeltas: _aio.UnaryUnaryMultiCallable[_splice_pb2.PredictDeltasRequest, _splice_pb2.PredictDeltasResponse]  # type: ignore[assignment]
    """Broad SpliceAI + Pangolin: each predictor's per-transcript deltas reduced to one gain and
    one loss on a shared orientation -> SPL_PRD input; the product-consequence call is the model's
    (SM11/SM18). See PredictDeltasResponse.
    """
    PredictSkipOutcome: _aio.UnaryUnaryMultiCallable[_splice_pb2.PredictSkipOutcomeRequest, _splice_pb2.PredictSkipOutcomeResponse]  # type: ignore[assignment]
    """The exon table (VariantValidator) + the RefSeq transcript sequence (NCBI Nucleotide): given a
    lost splice site, the skipped transcript's frame, PTC and NMD prediction — NOT whether the site
    is lost (that is PredictDeltas). See PredictSkipOutcomeResponse.
    """

class SpliceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def PredictDeltas(
        self,
        request: _splice_pb2.PredictDeltasRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_splice_pb2.PredictDeltasResponse, _abc.Awaitable[_splice_pb2.PredictDeltasResponse]]:
        """Broad SpliceAI + Pangolin: each predictor's per-transcript deltas reduced to one gain and
        one loss on a shared orientation -> SPL_PRD input; the product-consequence call is the model's
        (SM11/SM18). See PredictDeltasResponse.
        """

    @_abc_1.abstractmethod
    def PredictSkipOutcome(
        self,
        request: _splice_pb2.PredictSkipOutcomeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_splice_pb2.PredictSkipOutcomeResponse, _abc.Awaitable[_splice_pb2.PredictSkipOutcomeResponse]]:
        """The exon table (VariantValidator) + the RefSeq transcript sequence (NCBI Nucleotide): given a
        lost splice site, the skipped transcript's frame, PTC and NMD prediction — NOT whether the site
        is lost (that is PredictDeltas). See PredictSkipOutcomeResponse.
        """

def add_SpliceServicer_to_server(servicer: SpliceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
