# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from themis.rpc import store_pb2 as themis_dot_rpc_dot_store__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoreStub:
    """The store service: the versioned working document and the ephemeral /workspace archive.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutWorkingDocument = channel.unary_unary(
                '/themis.rpc.store.Store/PutWorkingDocument',
                request_serializer=themis_dot_rpc_dot_store__pb2.PutWorkingDocumentRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_store__pb2.PutWorkingDocumentResponse.FromString,
                _registered_method=True)
        self.GetWorkingDocument = channel.unary_unary(
                '/themis.rpc.store.Store/GetWorkingDocument',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_store__pb2.WorkingDocumentSnapshot.FromString,
                _registered_method=True)
        self.PutWorkspace = channel.stream_unary(
                '/themis.rpc.store.Store/PutWorkspace',
                request_serializer=themis_dot_rpc_dot_store__pb2.WorkspaceChunk.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_store__pb2.PutWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetWorkspace = channel.unary_stream(
                '/themis.rpc.store.Store/GetWorkspace',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_store__pb2.WorkspaceChunk.FromString,
                _registered_method=True)


class StoreServicer:
    """The store service: the versioned working document and the ephemeral /workspace archive.
    """

    def PutWorkingDocument(self, request, context):
        """Append a new immutable version of the working document. Each call mints a new server-assigned
        version, so the append is not idempotent and must not be auto-retried by a caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkingDocument(self, request, context):
        """The latest working-document version; a NOT_FOUND on the genuine first spawn is the server's,
        not modelled this slice.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutWorkspace(self, request_iterator, context):
        """Checkpoint the ephemeral /workspace remainder — an opaque tar archive, streamed in and
        overwrite-on-put.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Restore the ephemeral /workspace archive, streamed out; a NOT_FOUND when none yet is the
        server's.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutWorkingDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.PutWorkingDocument,
                    request_deserializer=themis_dot_rpc_dot_store__pb2.PutWorkingDocumentRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_store__pb2.PutWorkingDocumentResponse.SerializeToString,
            ),
            'GetWorkingDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkingDocument,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=themis_dot_rpc_dot_store__pb2.WorkingDocumentSnapshot.SerializeToString,
            ),
            'PutWorkspace': grpc.stream_unary_rpc_method_handler(
                    servicer.PutWorkspace,
                    request_deserializer=themis_dot_rpc_dot_store__pb2.WorkspaceChunk.FromString,
                    response_serializer=themis_dot_rpc_dot_store__pb2.PutWorkspaceResponse.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_stream_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=themis_dot_rpc_dot_store__pb2.WorkspaceChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.store.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.store.Store', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Store:
    """The store service: the versioned working document and the ephemeral /workspace archive.
    """

    @staticmethod
    def PutWorkingDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.store.Store/PutWorkingDocument',
            themis_dot_rpc_dot_store__pb2.PutWorkingDocumentRequest.SerializeToString,
            themis_dot_rpc_dot_store__pb2.PutWorkingDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkingDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.store.Store/GetWorkingDocument',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            themis_dot_rpc_dot_store__pb2.WorkingDocumentSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutWorkspace(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/themis.rpc.store.Store/PutWorkspace',
            themis_dot_rpc_dot_store__pb2.WorkspaceChunk.SerializeToString,
            themis_dot_rpc_dot_store__pb2.PutWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/themis.rpc.store.Store/GetWorkspace',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            themis_dot_rpc_dot_store__pb2.WorkspaceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
