"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
The `store` service: persist and restore a sandbox's /workspace across respawns
(docs/plans/self-hosted-sandbox.md §9), authorized per session (the bearer resolves via the
auth service, carried as x-themis-session-token metadata). This proto is the source of truth;
`regen` (buf generate) emits the themis/rpc/store stubs each consumer imports — the server subclasses the
servicer base, a caller uses the stub.

/workspace splits into two co-equal artifacts, both restored on spawn and checkpointed on idle:
the working document (the durable deliverable, versioned) and the ephemeral workspace (the rest
of the filesystem, an opaque tar archive streamed as bytes chunks).
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from themis.rpc import store_pb2 as _store_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class StoreStub:
    """The store service: the versioned working document and the ephemeral /workspace archive."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> StoreAsyncStub: ...
    PutWorkingDocument: _grpc.UnaryUnaryMultiCallable[_store_pb2.PutWorkingDocumentRequest, _store_pb2.PutWorkingDocumentResponse]
    """Append a new immutable version of the working document. Each call mints a new server-assigned
    version, so the append is not idempotent and must not be auto-retried by a caller.
    """
    GetWorkingDocument: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _store_pb2.WorkingDocumentSnapshot]
    """The latest working-document version; a NOT_FOUND on the genuine first spawn is the server's,
    not modelled this slice.
    """
    PutWorkspace: _grpc.StreamUnaryMultiCallable[_store_pb2.WorkspaceChunk, _store_pb2.PutWorkspaceResponse]
    """Checkpoint the ephemeral /workspace remainder — an opaque tar archive, streamed in and
    overwrite-on-put.
    """
    GetWorkspace: _grpc.UnaryStreamMultiCallable[_empty_pb2.Empty, _store_pb2.WorkspaceChunk]
    """Restore the ephemeral /workspace archive, streamed out; a NOT_FOUND when none yet is the
    server's.
    """

@_typing.type_check_only
class StoreAsyncStub(StoreStub):
    """The store service: the versioned working document and the ephemeral /workspace archive."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    PutWorkingDocument: _aio.UnaryUnaryMultiCallable[_store_pb2.PutWorkingDocumentRequest, _store_pb2.PutWorkingDocumentResponse]  # type: ignore[assignment]
    """Append a new immutable version of the working document. Each call mints a new server-assigned
    version, so the append is not idempotent and must not be auto-retried by a caller.
    """
    GetWorkingDocument: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _store_pb2.WorkingDocumentSnapshot]  # type: ignore[assignment]
    """The latest working-document version; a NOT_FOUND on the genuine first spawn is the server's,
    not modelled this slice.
    """
    PutWorkspace: _aio.StreamUnaryMultiCallable[_store_pb2.WorkspaceChunk, _store_pb2.PutWorkspaceResponse]  # type: ignore[assignment]
    """Checkpoint the ephemeral /workspace remainder — an opaque tar archive, streamed in and
    overwrite-on-put.
    """
    GetWorkspace: _aio.UnaryStreamMultiCallable[_empty_pb2.Empty, _store_pb2.WorkspaceChunk]  # type: ignore[assignment]
    """Restore the ephemeral /workspace archive, streamed out; a NOT_FOUND when none yet is the
    server's.
    """

class StoreServicer(metaclass=_abc_1.ABCMeta):
    """The store service: the versioned working document and the ephemeral /workspace archive."""

    @_abc_1.abstractmethod
    def PutWorkingDocument(
        self,
        request: _store_pb2.PutWorkingDocumentRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_store_pb2.PutWorkingDocumentResponse, _abc.Awaitable[_store_pb2.PutWorkingDocumentResponse]]:
        """Append a new immutable version of the working document. Each call mints a new server-assigned
        version, so the append is not idempotent and must not be auto-retried by a caller.
        """

    @_abc_1.abstractmethod
    def GetWorkingDocument(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_store_pb2.WorkingDocumentSnapshot, _abc.Awaitable[_store_pb2.WorkingDocumentSnapshot]]:
        """The latest working-document version; a NOT_FOUND on the genuine first spawn is the server's,
        not modelled this slice.
        """

    @_abc_1.abstractmethod
    def PutWorkspace(
        self,
        request_iterator: _MaybeAsyncIterator[_store_pb2.WorkspaceChunk],
        context: _ServicerContext,
    ) -> _typing.Union[_store_pb2.PutWorkspaceResponse, _abc.Awaitable[_store_pb2.PutWorkspaceResponse]]:
        """Checkpoint the ephemeral /workspace remainder — an opaque tar archive, streamed in and
        overwrite-on-put.
        """

    @_abc_1.abstractmethod
    def GetWorkspace(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_store_pb2.WorkspaceChunk], _abc.AsyncIterator[_store_pb2.WorkspaceChunk]]:
        """Restore the ephemeral /workspace archive, streamed out; a NOT_FOUND when none yet is the
        server's.
        """

def add_StoreServicer_to_server(servicer: StoreServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
