# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import transcript_pb2 as themis_dot_rpc_dot_transcript__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/transcript_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStructure = channel.unary_unary(
                '/themis.rpc.transcript.Transcript/GetStructure',
                request_serializer=themis_dot_rpc_dot_transcript__pb2.GetStructureRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_transcript__pb2.GetStructureResponse.FromString,
                _registered_method=True)
        self.AssessExonRelevance = channel.unary_unary(
                '/themis.rpc.transcript.Transcript/AssessExonRelevance',
                request_serializer=themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceResponse.FromString,
                _registered_method=True)


class TranscriptServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStructure(self, request, context):
        """VariantValidator transcript alignment: the exon table in genomic / n. / c. coordinates, plus
        where a supplied position sits in it (exon or intron, and its distance to each boundary).
        See GetStructureResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessExonRelevance(self, request, context):
        """GTEx + gnomAD pext/constraint + ClinVar density + VariantValidator (the exon table, and the
        gene's transcript inventory against the assessed exon) -> the exon axis of the mechanism x
        exon-relevance matrix; the All/Most/Few call is the model's. See AssessExonRelevanceResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStructure,
                    request_deserializer=themis_dot_rpc_dot_transcript__pb2.GetStructureRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_transcript__pb2.GetStructureResponse.SerializeToString,
            ),
            'AssessExonRelevance': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessExonRelevance,
                    request_deserializer=themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.transcript.Transcript', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.transcript.Transcript', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transcript:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.transcript.Transcript/GetStructure',
            themis_dot_rpc_dot_transcript__pb2.GetStructureRequest.SerializeToString,
            themis_dot_rpc_dot_transcript__pb2.GetStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessExonRelevance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.transcript.Transcript/AssessExonRelevance',
            themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceRequest.SerializeToString,
            themis_dot_rpc_dot_transcript__pb2.AssessExonRelevanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
