# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: themis/rpc/variant.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'themis/rpc/variant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from themis.evidence.models import evidence_pb2 as themis_dot_evidence_dot_models_dot_evidence__pb2
from themis.rpc import sandbox_options_pb2 as themis_dot_rpc_dot_sandbox__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18themis/rpc/variant.proto\x12\x12themis.rpc.variant\x1a\x1cgoogle/protobuf/struct.proto\x1a%themis/evidence/models/evidence.proto\x1a themis/rpc/sandbox_options.proto\"9\n\x10NormalizeRequest\x12\x0f\n\x07variant\x18\x01 \x01(\t\x12\x14\n\x0cgenome_build\x18\x02 \x01(\t\"\xc8\x03\n\x11NormalizeResponse\x12\x0c\n\x04\x63\x61id\x18\x01 \x01(\t\x12\x14\n\x0cgnomad_v4_id\x18\x02 \x01(\t\x12\x14\n\x0cgnomad_v2_id\x18\x03 \x01(\t\x12\x38\n\x0b\x63onsequence\x18\x04 \x01(\x0e\x32#.themis.evidence.models.Consequence\x12=\n\x0btranscripts\x18\x05 \x03(\x0b\x32(.themis.rpc.variant.TranscriptProjection\x12\x13\n\x0bgene_symbol\x18\x06 \x01(\t\x12\x0f\n\x07hgnc_id\x18\x07 \x01(\t\x12@\n\x12\x63linvar_variations\x18\x08 \x03(\x0b\x32$.themis.rpc.variant.ClinVarVariation\x12:\n\x0f\x63linvar_alleles\x18\t \x03(\x0b\x32!.themis.rpc.variant.ClinVarAllele\x12$\n\x03raw\x18\x0f \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x36\n\nprovenance\x18\x10 \x03(\x0b\x32\".themis.evidence.models.Provenance\"\xa4\x01\n\x14TranscriptProjection\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x0e\n\x06hgvs_c\x18\x02 \x01(\t\x12\x0e\n\x06hgvs_p\x18\x03 \x01(\t\x12\x13\n\x0bmane_select\x18\x04 \x01(\x08\x12\x1a\n\x12mane_plus_clinical\x18\x05 \x01(\x08\x12\x0f\n\x07sources\x18\x06 \x03(\t\x12\x16\n\x0e\x61\x63\x63\x65ssion_base\x18\x07 \x01(\t\"B\n\x10\x43linVarVariation\x12\x14\n\x0cvariation_id\x18\x01 \x01(\x05\x12\x0b\n\x03vcv\x18\x02 \x01(\t\x12\x0b\n\x03rcv\x18\x03 \x03(\t\":\n\rClinVarAllele\x12\x11\n\tallele_id\x18\x01 \x01(\x05\x12\x16\n\x0epreferred_name\x18\x02 \x01(\t2c\n\x07Variant\x12X\n\tNormalize\x12$.themis.rpc.variant.NormalizeRequest\x1a%.themis.rpc.variant.NormalizeResponseB\x04\x90\xb5\x18\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'themis.rpc.variant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\265\030\001'
  _globals['_NORMALIZEREQUEST']._serialized_start=151
  _globals['_NORMALIZEREQUEST']._serialized_end=208
  _globals['_NORMALIZERESPONSE']._serialized_start=211
  _globals['_NORMALIZERESPONSE']._serialized_end=667
  _globals['_TRANSCRIPTPROJECTION']._serialized_start=670
  _globals['_TRANSCRIPTPROJECTION']._serialized_end=834
  _globals['_CLINVARVARIATION']._serialized_start=836
  _globals['_CLINVARVARIATION']._serialized_end=902
  _globals['_CLINVARALLELE']._serialized_start=904
  _globals['_CLINVARALLELE']._serialized_end=962
  _globals['_VARIANT']._serialized_start=964
  _globals['_VARIANT']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
