"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
variant: the spine. One transcript HGVS in, the canonical allele and its projections out, so every
other evidence interface joins on a shared key and the right SVCv4 decision tree is selected.
Design: docs/design/evidence-interfaces.md.

Modelled from:
  ClinGen Allele Registry (allele lookup by HGVS, and its ClinVar crosswalk): `ClinVarVariation`,
    `ClinVarAllele` carry the crosswalk's fields under its names; `caid` is its canonical allele id.
  This interface's own design: `NormalizeRequest`, `NormalizeResponse`, `TranscriptProjection` —
    the Allele Registry, VariantValidator and Ensembl VEP re-keyed onto one join key; no upstream
    returns this shape.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import variant_pb2 as _variant_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VariantStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VariantAsyncStub: ...
    Normalize: _grpc.UnaryUnaryMultiCallable[_variant_pb2.NormalizeRequest, _variant_pb2.NormalizeResponse]
    """Canonicalise the variant, project transcripts, set the routing consequence — the join
    key every other interface's facts hang on. ClinGen Allele Registry + VariantValidator + VEP.
    """

@_typing.type_check_only
class VariantAsyncStub(VariantStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Normalize: _aio.UnaryUnaryMultiCallable[_variant_pb2.NormalizeRequest, _variant_pb2.NormalizeResponse]  # type: ignore[assignment]
    """Canonicalise the variant, project transcripts, set the routing consequence — the join
    key every other interface's facts hang on. ClinGen Allele Registry + VariantValidator + VEP.
    """

class VariantServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Normalize(
        self,
        request: _variant_pb2.NormalizeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_variant_pb2.NormalizeResponse, _abc.Awaitable[_variant_pb2.NormalizeResponse]]:
        """Canonicalise the variant, project transcripts, set the routing consequence — the join
        key every other interface's facts hang on. ClinGen Allele Registry + VariantValidator + VEP.
        """

def add_VariantServicer_to_server(servicer: VariantServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
