"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
vep: Ensembl's Variant Effect Predictor, the consolidator — one call carrying the routing
consequence, the calibrated predictor scores and a colocated-variant snapshot.
Design: docs/design/evidence-interfaces.md.

Modelled from:
  Ensembl VEP REST (HGVS endpoint): `AnnotateResponse.raw` is its JSON verbatim, and `predictors`
    names each score by the VEP flag or dbNSFP-plugin column that serves it.
  This interface's own design: `AnnotateRequest` (the closed predictor set, the GRCh38 pin), and
    `AnnotateResponse.most_severe_consequence`, VEP's term re-encoded onto the shared SVCv4 enum.

EVALUATION ONLY, AGAINST A DRAFT STANDARD. SVCv4 is a July 2026 pilot: its point values,
thresholds and code names may change before publication, so the SVCv4 codes named throughout
these comments are provisional. Nothing here is validated for clinical or diagnostic use, and a
classification composed from these facts is not a clinical variant classification.

Auth is per the service pattern (services.md): the session token arrives as x-themis-session-token
metadata and resolves via themis.clients.auth; it is never a message field.

The shared value types (Provenance, GenomicSpan, the routing Consequence):
themis/evidence/models/evidence.proto.
"""

from collections import abc as _abc
from grpc import aio as _aio
from themis.rpc import vep_pb2 as _vep_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VepStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VepAsyncStub: ...
    Annotate: _grpc.UnaryUnaryMultiCallable[_vep_pb2.AnnotateRequest, _vep_pb2.AnnotateResponse]
    """Ensembl VEP: routing consequence + the policy's predictor score (MIS_PRD) + SpliceAI (SPL_PRD)
    deltas + a ClinVar/gnomAD snapshot (context only). See AnnotateResponse.
    """

@_typing.type_check_only
class VepAsyncStub(VepStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Annotate: _aio.UnaryUnaryMultiCallable[_vep_pb2.AnnotateRequest, _vep_pb2.AnnotateResponse]  # type: ignore[assignment]
    """Ensembl VEP: routing consequence + the policy's predictor score (MIS_PRD) + SpliceAI (SPL_PRD)
    deltas + a ClinVar/gnomAD snapshot (context only). See AnnotateResponse.
    """

class VepServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Annotate(
        self,
        request: _vep_pb2.AnnotateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_vep_pb2.AnnotateResponse, _abc.Awaitable[_vep_pb2.AnnotateResponse]]:
        """Ensembl VEP: routing consequence + the policy's predictor score (MIS_PRD) + SpliceAI (SPL_PRD)
        deltas + a ClinVar/gnomAD snapshot (context only). See AnnotateResponse.
        """

def add_VepServicer_to_server(servicer: VepServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
