# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: themis/evidence/models/evidence.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'themis/evidence/models/evidence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%themis/evidence/models/evidence.proto\x12\x16themis.evidence.models\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\nProvenance\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x18\n\x10\x64\x61taset_versions\x18\x02 \x03(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\x30\n\x0cretrieved_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\")\n\x0bGenomicSpan\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03*\x85\x03\n\x0b\x43onsequence\x12\x1b\n\x17\x43ONSEQUENCE_UNSPECIFIED\x10\x00\x12\x18\n\x14\x43ONSEQUENCE_MISSENSE\x10\x01\x12\x18\n\x14\x43ONSEQUENCE_NONSENSE\x10\x02\x12\x1a\n\x16\x43ONSEQUENCE_FRAMESHIFT\x10\x03\x12 \n\x1c\x43ONSEQUENCE_CANONICAL_SPLICE\x10\x04\x12\x18\n\x14\x43ONSEQUENCE_INTRONIC\x10\x05\x12\x1a\n\x16\x43ONSEQUENCE_SYNONYMOUS\x10\x06\x12\x1d\n\x19\x43ONSEQUENCE_INFRAME_INDEL\x10\x07\x12\x1a\n\x16\x43ONSEQUENCE_START_LOST\x10\x08\x12\x19\n\x15\x43ONSEQUENCE_STOP_LOST\x10\t\x12\x1d\n\x19\x43ONSEQUENCE_EXON_DELETION\x10\n\x12 \n\x1c\x43ONSEQUENCE_EXON_DUPLICATION\x10\x0b\x12\x1a\n\x16\x43ONSEQUENCE_NON_CODING\x10\x0c*\x82\x02\n\x0bInheritance\x12\x1b\n\x17INHERITANCE_UNSPECIFIED\x10\x00\x12\"\n\x1eINHERITANCE_AUTOSOMAL_DOMINANT\x10\x01\x12#\n\x1fINHERITANCE_AUTOSOMAL_RECESSIVE\x10\x02\x12\x18\n\x14INHERITANCE_X_LINKED\x10\x03\x12\x18\n\x14INHERITANCE_Y_LINKED\x10\x04\x12\x1d\n\x19INHERITANCE_MITOCHONDRIAL\x10\x05\x12\x1c\n\x18INHERITANCE_SEMIDOMINANT\x10\x06\x12\x1c\n\x18INHERITANCE_UNDETERMINED\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'themis.evidence.models.evidence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSEQUENCE']._serialized_start=263
  _globals['_CONSEQUENCE']._serialized_end=652
  _globals['_INHERITANCE']._serialized_start=655
  _globals['_INHERITANCE']._serialized_end=913
  _globals['_PROVENANCE']._serialized_start=98
  _globals['_PROVENANCE']._serialized_end=217
  _globals['_GENOMICSPAN']._serialized_start=219
  _globals['_GENOMICSPAN']._serialized_end=260
# @@protoc_insertion_point(module_scope)
