# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: themis/widgets/models/checklist.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'themis/widgets/models/checklist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from themis.widgets.models import widget_pb2 as themis_dot_widgets_dot_models_dot_widget__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%themis/widgets/models/checklist.proto\x12\x15themis.widgets.models\x1a\x1b\x62uf/validate/validate.proto\x1a\"themis/widgets/models/widget.proto\"\xa8\x03\n\tChecklist\x12\xa4\x01\n\x05items\x18\x01 \x03(\x0b\x32%.themis.widgets.models.Checklist.ItemBn\xbaHk\x92\x01\x04\x08\x01\x10\x64\xba\x01\x61\n\x1a\x63hecklist.items.unique_ids\x12!every item needs an id of its own\x1a this.map(item, item.id).unique()\x1a=\n\x08\x43itation\x12\x18\n\x06\x64oc_id\x18\x01 \x01(\tB\x08\xbaH\x05r\x03\xb0\x01\x01\x12\x17\n\x05quote\x18\x02 \x01(\tB\x08\xbaH\x05r\x03\x18\xd0\x0f\x1a\xae\x01\n\x04Item\x12\x15\n\x07\x63hecked\x18\x01 \x01(\x08\x42\x04\xaa\xb6\x18\x00\x12\x37\n\x02id\x18\x02 \x01(\tB+\xbaH$r\"\x10\x01\x18@2\x1c^[A-Za-z0-9][A-Za-z0-9_.-]*$\xb0\xb6\x18\x01\x12\x19\n\x05label\x18\x03 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\xe8\x07\x12;\n\x08\x63itation\x18\x04 \x01(\x0b\x32).themis.widgets.models.Checklist.Citation:\x04\xa0\xb6\x18\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'themis.widgets.models.checklist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKLIST_CITATION'].fields_by_name['doc_id']._loaded_options = None
  _globals['_CHECKLIST_CITATION'].fields_by_name['doc_id']._serialized_options = b'\272H\005r\003\260\001\001'
  _globals['_CHECKLIST_CITATION'].fields_by_name['quote']._loaded_options = None
  _globals['_CHECKLIST_CITATION'].fields_by_name['quote']._serialized_options = b'\272H\005r\003\030\320\017'
  _globals['_CHECKLIST_ITEM'].fields_by_name['checked']._loaded_options = None
  _globals['_CHECKLIST_ITEM'].fields_by_name['checked']._serialized_options = b'\252\266\030\000'
  _globals['_CHECKLIST_ITEM'].fields_by_name['id']._loaded_options = None
  _globals['_CHECKLIST_ITEM'].fields_by_name['id']._serialized_options = b'\272H$r\"\020\001\030@2\034^[A-Za-z0-9][A-Za-z0-9_.-]*$\260\266\030\001'
  _globals['_CHECKLIST_ITEM'].fields_by_name['label']._loaded_options = None
  _globals['_CHECKLIST_ITEM'].fields_by_name['label']._serialized_options = b'\272H\007r\005\020\001\030\350\007'
  _globals['_CHECKLIST'].fields_by_name['items']._loaded_options = None
  _globals['_CHECKLIST'].fields_by_name['items']._serialized_options = b'\272Hk\222\001\004\010\001\020d\272\001a\n\032checklist.items.unique_ids\022!every item needs an id of its own\032 this.map(item, item.id).unique()'
  _globals['_CHECKLIST']._loaded_options = None
  _globals['_CHECKLIST']._serialized_options = b'\240\266\030\001'
  _globals['_CHECKLIST']._serialized_start=130
  _globals['_CHECKLIST']._serialized_end=554
  _globals['_CHECKLIST_CITATION']._serialized_start=310
  _globals['_CHECKLIST_CITATION']._serialized_end=371
  _globals['_CHECKLIST_ITEM']._serialized_start=374
  _globals['_CHECKLIST_ITEM']._serialized_end=548
# @@protoc_insertion_point(module_scope)
