// The literature view model — the BFF↔frontend shapes for the literature read surface, generated by
// protobuf-es from schema/proto/themis/rpc/literature.proto. App code imports the message types and
// schemas from here rather than the generated path. `DescribePaper` is served as proto3-JSON
// (toJson / fromJson); content objects (markdown, pdf, files) are raw bytes over their own routes,
// not proto.

export * from "@/gen/themis/rpc/literature_pb";
