# generated by datamodel-codegen:
#   filename:  demo.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class Colour(StrEnum):
    red = 'red'
    green = 'green'
    blue = 'blue'


class Widget(BaseModel):
    name: str
    colour: Colour


class Catalogue(BaseModel):
    widgets: list[Widget]
