# generated by datamodel-codegen:
#   filename:  features.schema.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class Colour(StrEnum):
    red = 'red'
    green = 'green'
    blue = 'blue'


class OptionalHolder(BaseModel):
    required_field: str
    optional_field: str | None = None


class DefaultHolder(BaseModel):
    flagged: bool | None = False


class LiteralHolder(BaseModel):
    kind: Literal['widget']


class FreeToRead(BaseModel):
    access: Literal['free-to-read']


class Licensed(BaseModel):
    access: Literal['licensed']
    publisher: str


class Access(RootModel[FreeToRead | Licensed]):
    root: FreeToRead | Licensed


class Inner(BaseModel):
    value: str


class Outer(BaseModel):
    inner: Inner


class ArrayHolder(BaseModel):
    tags: list[str]
    palette: list[Colour]


class ScalarHolder(BaseModel):
    count: int = Field(..., ge=-2147483648, le=2147483647)
    ratio: float
    when: AwareDatetime
    day: date
    link: AnyUrl


class EnumHolder(BaseModel):
    colour: Colour


class AccessHolder(BaseModel):
    access: Access
