# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import cspec_pb2 as themis_dot_rpc_dot_cspec__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/cspec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CspecStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSpecifications = channel.unary_unary(
                '/themis.rpc.cspec.Cspec/ListSpecifications',
                request_serializer=themis_dot_rpc_dot_cspec__pb2.ListSpecificationsRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_cspec__pb2.ListSpecificationsResponse.FromString,
                _registered_method=True)


class CspecServicer:
    """Missing associated documentation comment in .proto file."""

    def ListSpecifications(self, request, context):
        """ClinGen CSpec Registry: every criteria specification whose rule set names the gene, with
        each ACMG/AMP-2015 criterion's applicability, per-strength gene-specific wording and thresholds,
        the panel's cited works and attachments, and the DOI + version a quotation is attributed to.
        Reduced across nothing and selected from by nothing: a gene can be covered by a multi-gene legacy
        document and by the per-gene one carved out of it, and which governs is each one's `status`. A
        gene no panel has specified and a symbol the registry's gene table has no entry for are distinct
        answers (`coverage`), neither an error. The derived leaves are `status` (over the document's
        state history and its two legacy flags), the registry URLs and the rendered author strings.

        SM3 ranks a curated VCEP threshold first among its DAFT methods, and this is how that method is
        reached. It is NOT an SVCv4 profile: the codes, strengths and points here are ACMG/AMP-2015 and
        the panel's own, and a threshold enters SM3's ordering at the rung ITS derivation earns rather
        than at method 1 because a VCEP published it. See ListSpecificationsResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CspecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSpecifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSpecifications,
                    request_deserializer=themis_dot_rpc_dot_cspec__pb2.ListSpecificationsRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_cspec__pb2.ListSpecificationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.cspec.Cspec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.cspec.Cspec', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cspec:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSpecifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.cspec.Cspec/ListSpecifications',
            themis_dot_rpc_dot_cspec__pb2.ListSpecificationsRequest.SerializeToString,
            themis_dot_rpc_dot_cspec__pb2.ListSpecificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
