# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import hello_pb2 as themis_dot_rpc_dot_hello__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/hello_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelloStub:
    """The hello service: echo the caller's note against its resolved session binding.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/themis.rpc.hello.Hello/SayHello',
                request_serializer=themis_dot_rpc_dot_hello__pb2.SayHelloRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_hello__pb2.SayHelloResponse.FromString,
                _registered_method=True)


class HelloServicer:
    """The hello service: echo the caller's note against its resolved session binding.
    """

    def SayHello(self, request, context):
        """Resolve the request's session token and echo the note against the bound Analysis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=themis_dot_rpc_dot_hello__pb2.SayHelloRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_hello__pb2.SayHelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.hello.Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.hello.Hello', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hello:
    """The hello service: echo the caller's note against its resolved session binding.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.hello.Hello/SayHello',
            themis_dot_rpc_dot_hello__pb2.SayHelloRequest.SerializeToString,
            themis_dot_rpc_dot_hello__pb2.SayHelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
