# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from themis.rpc import variant_pb2 as themis_dot_rpc_dot_variant__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in themis/rpc/variant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VariantStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Normalize = channel.unary_unary(
                '/themis.rpc.variant.Variant/Normalize',
                request_serializer=themis_dot_rpc_dot_variant__pb2.NormalizeRequest.SerializeToString,
                response_deserializer=themis_dot_rpc_dot_variant__pb2.NormalizeResponse.FromString,
                _registered_method=True)


class VariantServicer:
    """Missing associated documentation comment in .proto file."""

    def Normalize(self, request, context):
        """Canonicalise the variant, project transcripts, set the routing consequence — the join
        key every other interface's facts hang on. ClinGen Allele Registry + VariantValidator + VEP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VariantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Normalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Normalize,
                    request_deserializer=themis_dot_rpc_dot_variant__pb2.NormalizeRequest.FromString,
                    response_serializer=themis_dot_rpc_dot_variant__pb2.NormalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'themis.rpc.variant.Variant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('themis.rpc.variant.Variant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Variant:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Normalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/themis.rpc.variant.Variant/Normalize',
            themis_dot_rpc_dot_variant__pb2.NormalizeRequest.SerializeToString,
            themis_dot_rpc_dot_variant__pb2.NormalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
