"""Generate the sandbox agent-exposure surface from the `agent_exposed` proto option (sandbox-rpc-exposure.md).

`buf build` compiles the module to a `FileDescriptorSet`; every file carrying
`option (themis.rpc.agent_exposed) = true` contributes all of its services' methods to the hatch allowlist.
A file without the option contributes nothing — the default is fail-closed. The allowlist is written to a
generated module the worker imports (`themis/services/sandbox_worker/_generated.py`), committed and gated by
the schema-freshness check like the proto stubs.
"""

from __future__ import annotations

import pathlib
import subprocess

from google.protobuf import descriptor_pb2

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_GENERATED = _REPO_ROOT / 'themis' / 'services' / 'sandbox_worker' / '_generated.py'

_HEADER = '''\
# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""Generated sandbox agent-exposure surface: the methods the guest may reach through the hatch."""

from __future__ import annotations
'''


def build_image() -> bytes:
    """Compile the module to a serialized `FileDescriptorSet` with `buf build`. Requires `buf` on PATH.

    stderr is left inherited so `buf`'s own diagnostics reach the console on failure (fail-loud); only the
    binary image on stdout is captured.
    """
    built = subprocess.run(
        ['buf', 'build', '--output', '-#format=binpb'],  # noqa: S607
        cwd=_REPO_ROOT,
        check=True,
        stdout=subprocess.PIPE,
    )
    return built.stdout


def service_files(image_bytes: bytes) -> set[str]:
    """The names of the module's files that declare at least one service — the inputs to the gRPC-stub pass."""
    image = descriptor_pb2.FileDescriptorSet()
    image.ParseFromString(image_bytes)
    return {file.name for file in image.file if file.service}


def _exposed_methods(image_bytes: bytes) -> list[str]:
    """The `/pkg.Service/Method` path of every method of every service in an `agent_exposed` file, sorted."""
    # Imported here, not at module top: the stub is (re)generated during this same regen run, so a top-level
    # import could bind a stale or not-yet-written module. Registering the extension must also precede the
    # parse below, or the C++/upb backend keeps the option as an unknown field.
    from themis.rpc import sandbox_options_pb2  # noqa: PLC0415

    image = descriptor_pb2.FileDescriptorSet()
    image.ParseFromString(image_bytes)
    exposed = sandbox_options_pb2.agent_exposed
    methods = []
    for file in image.file:
        # grpcio-tools types the extension as a bare FieldDescriptor, not the handle Extensions[] expects.
        if not file.options.Extensions[exposed]:  # pyright: ignore[reportArgumentType]
            continue
        if not file.package:
            raise ValueError(f'agent_exposed file {file.name!r} has no package; its allowlist path would be malformed')
        for service in file.service:
            methods += [f'/{file.package}.{service.name}/{method.name}' for method in service.method]
    return sorted(methods)


def _render(methods: list[str]) -> str:
    body = ''.join(f'        {method!r},\n' for method in methods)
    return f'{_HEADER}\nGUEST_METHODS = frozenset(\n    {{\n{body}    }}\n)\n'


def generate(image_bytes: bytes) -> None:
    """Write the generated allowlist from a `build_image()` descriptor set."""
    _GENERATED.write_text(_render(_exposed_methods(image_bytes)), encoding='utf-8')
