"""Read the sandbox agent-exposure surface off the `agent_exposed` proto option (sandbox-rpc-exposure.md).

`buf build` compiles the module to a `FileDescriptorSet`; every rpc carrying
`option (themis.rpc.agent_exposed) = true` joins the hatch allowlist. An rpc without the option contributes
nothing — the default is fail-closed. Two modules fall out of it, both committed and gated by the
schema-freshness check like the proto stubs: the allowlist the worker's hatch enforces
(`themis/services/sandbox_worker/_generated.py`), and the guest's accessors
(`themis/services/sandbox_worker/guest/services.py`) — one per service with a marked rpc, handing back the
service's stub over the hatch channel. The stub the guest imports is generated from the guest's own contract
tree (`tools.schema.guest_contract`), which carries the marked rpcs and nothing else, so the accessor offers
exactly what the hatch admits. One option, so none of the three can disagree about what is exposed.
"""

from __future__ import annotations

import itertools
import operator
import pathlib
import subprocess
from typing import NamedTuple

from google.protobuf import descriptor_pb2

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_GENERATED = _REPO_ROOT / 'themis' / 'services' / 'sandbox_worker' / '_generated.py'
_GUEST_SERVICES = _REPO_ROOT / 'themis' / 'services' / 'sandbox_worker' / 'guest' / 'services.py'

PROVENANCE = """\
# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""

_HEADER = f'''\
{PROVENANCE}"""Generated sandbox agent-exposure surface: the methods the guest may reach through the hatch."""

from __future__ import annotations
'''

_GUEST_SERVICES_HEADER = f'''\
{PROVENANCE}"""Generated accessors for the internal Themis services the guest may reach through the hatch.

Shipped into the guest rootfs as ``themis.agent.services`` — the stable name the agent's code-mode snippets
import. Each accessor is named for its proto package's last segment and returns the service's stub over the one
hatch channel, which supplies the deadline and carries the session token. The stub is the one the guest's own
contract tree generates, so it offers exactly the rpcs the hatch admits. Get one, keep it, and call it.
"""

from __future__ import annotations
'''


def build_image() -> bytes:
    """Compile the module to a serialized `FileDescriptorSet` with `buf build`. Requires `buf` on PATH.

    stderr is left inherited so `buf`'s own diagnostics reach the console on failure (fail-loud); only the
    binary image on stdout is captured. The image carries source info: the guest contract tree is cut by it.
    """
    built = subprocess.run(
        ['buf', 'build', '--output', '-#format=binpb'],  # noqa: S607
        cwd=_REPO_ROOT,
        check=True,
        stdout=subprocess.PIPE,
    )
    return built.stdout


def image_of(image_bytes: bytes) -> descriptor_pb2.FileDescriptorSet:
    """Parse a serialized `FileDescriptorSet`."""
    image = descriptor_pb2.FileDescriptorSet()
    image.ParseFromString(image_bytes)
    return image


def service_files(image_bytes: bytes) -> set[str]:
    """The names of the module's files that declare at least one service — the inputs to the gRPC-stub pass."""
    return {file.name for file in image_of(image_bytes).file if file.service}


class Module(NamedTuple):
    """Where protoc put a file's generated Python: the package its directory became, and the module's name."""

    package: str
    name: str


def module_of(file_name: str, suffix: str) -> Module:
    """The generated module, named as protoc names it: off the file path rather than the proto package."""
    path = pathlib.PurePosixPath(file_name)
    return Module(package=str(path.parent).replace('/', '.'), name=f'{path.stem}{suffix}')


class MarkedService(NamedTuple):
    """A service with at least one marked rpc: where it is declared, and which of its rpcs the agent may call."""

    file: str
    package: str
    name: str
    methods: tuple[str, ...]

    @property
    def full_name(self) -> str:
        return f'{self.package}.{self.name}'

    @property
    def accessor(self) -> str:
        """The word the service is known by everywhere else: its proto package's last segment."""
        return self.package.rsplit('.', 1)[-1]

    @property
    def stub_module(self) -> Module:
        return module_of(self.file, '_pb2_grpc')

    @property
    def stub(self) -> str:
        return f'{self.name}Stub'


def marked_services(image_bytes: bytes) -> list[MarkedService]:
    """Every service with a marked rpc, its marked rpcs in declaration order, sorted by accessor name.

    Raises:
        ValueError: If no rpc is marked at all (an empty surface is never intended, so it means the option was
            not read off the image), if a marked rpc sits in a file with no package (its allowlist path would be
            malformed), or if two services would collide on a name the accessor module has one namespace for.
    """
    # Imported here, not at module top: the stub is (re)generated during this same regen run, so a top-level
    # import could bind a stale or not-yet-written module. Registering the extension must precede the parse
    # below, or the C++/upb backend keeps the option as an unknown field.
    from themis.rpc import sandbox_options_pb2  # noqa: PLC0415

    exposed = sandbox_options_pb2.agent_exposed
    services: list[MarkedService] = []
    for file in image_of(image_bytes).file:
        for service in file.service:
            # grpcio-tools types the extension as a bare FieldDescriptor, not the handle Extensions[] expects.
            methods = tuple(
                method.name
                for method in service.method
                if method.options.Extensions[exposed]  # pyright: ignore[reportArgumentType]
            )
            if not methods:
                continue
            if not file.package:
                raise ValueError(f'agent_exposed rpc {methods[0]!r} in {file.name!r} has no package')
            services.append(MarkedService(file.name, file.package, service.name, methods))
    if not services:
        raise ValueError('no rpc carries agent_exposed: nothing is marked, or the option was not read off the image')
    _reject_collisions(services)
    return sorted(services, key=operator.attrgetter('accessor'))


def _reject_collisions(services: list[MarkedService]) -> None:
    """The accessor module has two flat namespaces; a name two services would share in either is an error.

    Raises:
        ValueError: If two services take the same accessor name, or import stub modules of the same name from
            different packages — each would rebind the other's definition, so the collision has to be resolved in
            the protos rather than silently resolved here.
    """

    def duplicates(names: list[str]) -> list[str]:
        return sorted({name for name in names if names.count(name) > 1})

    if found := duplicates([s.accessor for s in services]):
        raise ValueError(f'agent-exposed services collide on accessor name {found}')
    if found := duplicates([module.name for module in sorted({s.stub_module for s in services})]):
        raise ValueError(f'agent-exposed services import stub modules of one name from different packages {found}')


def exposed_methods(services: list[MarkedService]) -> list[str]:
    """The `/pkg.Service/Method` path of every marked rpc, sorted."""
    return sorted(f'/{s.full_name}/{m}' for s in services for m in s.methods)


def _render_allowlist(methods: list[str]) -> str:
    body = ''.join(f'        {method!r},\n' for method in methods)
    return f'{_HEADER}\nGUEST_METHODS = frozenset(\n    {{\n{body}    }}\n)\n'


def render_guest_services(services: list[MarkedService]) -> str:
    """The accessor module: one function per marked service, returning its stub over the hatch channel."""
    modules = sorted({s.stub_module for s in services})
    imports = ''
    for package, group in itertools.groupby(modules, key=operator.attrgetter('package')):
        names = ''.join(f'    {module.name},\n' for module in group)
        imports += f'\nfrom {package} import (\n{names})\n'
    body = ''.join(
        f'\n\ndef {s.accessor}() -> {s.stub_module.name}.{s.stub}:\n'
        f'    return {s.stub_module.name}.{s.stub}(channel.to_hatch())\n'
        for s in services
    )
    return f'{_GUEST_SERVICES_HEADER}{imports}\nfrom . import channel\n{body}'


def generate(image_bytes: bytes) -> list[MarkedService]:
    """Write the generated allowlist and guest accessors from a `build_image()` descriptor set.

    Returns:
        The marked services, for the guest contract tree to be cut from the same reading of the option.
    """
    services = marked_services(image_bytes)
    _GENERATED.write_text(_render_allowlist(exposed_methods(services)), encoding='utf-8')
    _GUEST_SERVICES.write_text(render_guest_services(services), encoding='utf-8')
    return services
