"""Generate the sandbox agent-exposure surface from the `agent_exposed` proto option (sandbox-rpc-exposure.md).

`buf build` compiles the module to a `FileDescriptorSet`; every file carrying
`option (themis.rpc.agent_exposed) = true` contributes all of its services' methods to the hatch allowlist.
A file without the option contributes nothing — the default is fail-closed. Two modules fall out of it, both
committed and gated by the schema-freshness check like the proto stubs: the allowlist the worker's hatch
enforces (`themis/services/sandbox_worker/_generated.py`), and the stub accessors the guest calls the exposed
services through (`themis/services/sandbox_worker/guest/services.py`). One option, so the two cannot disagree
about what is exposed.
"""

from __future__ import annotations

import itertools
import operator
import pathlib
import subprocess
from typing import NamedTuple

from google.protobuf import descriptor_pb2

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_GENERATED = _REPO_ROOT / 'themis' / 'services' / 'sandbox_worker' / '_generated.py'
_GUEST_SERVICES = _REPO_ROOT / 'themis' / 'services' / 'sandbox_worker' / 'guest' / 'services.py'

_PROVENANCE = """\
# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""

_HEADER = f'''\
{_PROVENANCE}"""Generated sandbox agent-exposure surface: the methods the guest may reach through the hatch."""

from __future__ import annotations
'''

_GUEST_SERVICES_HEADER = f'''\
{_PROVENANCE}"""Generated stub accessors for the internal Themis services the guest may reach through the hatch.

Shipped into the guest rootfs as ``themis.agent.services`` — the stable name the agent's code-mode snippets
import. Each accessor is named for its proto package's last segment, and returns a stub over the one hatch
channel, which supplies the deadline and carries the session token. Get a stub, keep it, and call it.
"""

from __future__ import annotations
'''


def build_image() -> bytes:
    """Compile the module to a serialized `FileDescriptorSet` with `buf build`. Requires `buf` on PATH.

    stderr is left inherited so `buf`'s own diagnostics reach the console on failure (fail-loud); only the
    binary image on stdout is captured.
    """
    built = subprocess.run(
        ['buf', 'build', '--output', '-#format=binpb'],  # noqa: S607
        cwd=_REPO_ROOT,
        check=True,
        stdout=subprocess.PIPE,
    )
    return built.stdout


def service_files(image_bytes: bytes) -> set[str]:
    """The names of the module's files that declare at least one service — the inputs to the gRPC-stub pass."""
    image = descriptor_pb2.FileDescriptorSet()
    image.ParseFromString(image_bytes)
    return {file.name for file in image.file if file.service}


def _exposed_files(image_bytes: bytes) -> list[descriptor_pb2.FileDescriptorProto]:
    """Every file in the image carrying `option (themis.rpc.agent_exposed) = true`."""
    # Imported here, not at module top: the stub is (re)generated during this same regen run, so a top-level
    # import could bind a stale or not-yet-written module. Registering the extension must also precede the
    # parse below, or the C++/upb backend keeps the option as an unknown field.
    from themis.rpc import sandbox_options_pb2  # noqa: PLC0415

    image = descriptor_pb2.FileDescriptorSet()
    image.ParseFromString(image_bytes)
    exposed = sandbox_options_pb2.agent_exposed
    files = []
    for file in image.file:
        # grpcio-tools types the extension as a bare FieldDescriptor, not the handle Extensions[] expects.
        if not file.options.Extensions[exposed]:  # pyright: ignore[reportArgumentType]
            continue
        if not file.package:
            raise ValueError(f'agent_exposed file {file.name!r} has no package; its allowlist path would be malformed')
        files.append(file)
    return files


def _exposed_methods(image_bytes: bytes) -> list[str]:
    """The `/pkg.Service/Method` path of every method of every service in an `agent_exposed` file, sorted."""
    return sorted(
        f'/{file.package}.{service.name}/{method.name}'
        for file in _exposed_files(image_bytes)
        for service in file.service
        for method in service.method
    )


class _Accessor(NamedTuple):
    """One generated guest accessor: what the agent calls it, and the stub it hands back."""

    name: str
    package: str
    module: str
    stub: str


def _accessors(image_bytes: bytes) -> list[_Accessor]:
    """An accessor per service in an `agent_exposed` file, sorted by the name the agent calls it.

    The name is the proto package's last segment — the word the service is known by everywhere else, so the
    agent's prompt, the allowlist and this module all say `gnomad`. The stub's module follows protoc's own
    rule, off the file path rather than the package, since that is what protoc named the file it emitted.

    Raises:
        ValueError: If two services would take the same accessor name. One name can only hand back one stub,
            so the collision has to be resolved in the protos rather than silently resolved here.
    """
    accessors = []
    for file in _exposed_files(image_bytes):
        path = pathlib.PurePosixPath(file.name)
        for service in file.service:
            accessors.append(
                _Accessor(
                    name=file.package.rsplit('.', 1)[-1],
                    package=str(path.parent).replace('/', '.'),
                    module=f'{path.stem}_pb2_grpc',
                    stub=f'{service.name}Stub',
                )
            )
    collisions = {a.name for a in accessors if sum(other.name == a.name for other in accessors) > 1}
    if collisions:
        raise ValueError(f'agent-exposed services collide on accessor name {sorted(collisions)}')
    return sorted(accessors)


def _render(methods: list[str]) -> str:
    body = ''.join(f'        {method!r},\n' for method in methods)
    return f'{_HEADER}\nGUEST_METHODS = frozenset(\n    {{\n{body}    }}\n)\n'


def _render_guest_services(accessors: list[_Accessor]) -> str:
    by_package = sorted(accessors, key=operator.attrgetter('package', 'module'))
    imports = ''
    for package, group in itertools.groupby(by_package, key=operator.attrgetter('package')):
        modules = ''.join(f'    {module},\n' for module in sorted({accessor.module for accessor in group}))
        imports += f'from {package} import (\n{modules})\n'
    body = ''.join(
        f'\n\ndef {a.name}() -> {a.module}.{a.stub}:\n    return {a.module}.{a.stub}(channel.to_hatch())\n'
        for a in accessors
    )
    return f'{_GUEST_SERVICES_HEADER}\n{imports}\nfrom . import channel\n{body}'


def generate(image_bytes: bytes) -> None:
    """Write the generated allowlist and guest stub accessors from a `build_image()` descriptor set."""
    _GENERATED.write_text(_render(_exposed_methods(image_bytes)), encoding='utf-8')
    _GUEST_SERVICES.write_text(_render_guest_services(_accessors(image_bytes)), encoding='utf-8')
