# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""Generated accessors for the internal Themis services the guest may reach through the hatch.

Shipped into the guest rootfs as ``themis.agent.services`` — the stable name the agent's code-mode snippets
import. Each accessor is named for its proto package's last segment and returns the service's stub over the one
hatch channel, which supplies the deadline and carries the session token. The stub is the one the guest's own
contract tree generates, so it offers exactly the rpcs the hatch admits. Get one, keep it, and call it.
"""

from __future__ import annotations

from themis.rpc import (
    clinvar_pb2_grpc,
    cspec_pb2_grpc,
    gene_disease_pb2_grpc,
    gnomad_pb2_grpc,
    hello_pb2_grpc,
    mavedb_pb2_grpc,
    splice_pb2_grpc,
    transcript_pb2_grpc,
    variant_pb2_grpc,
    vep_pb2_grpc,
)

from . import channel


def clinvar() -> clinvar_pb2_grpc.ClinVarStub:
    return clinvar_pb2_grpc.ClinVarStub(channel.to_hatch())


def cspec() -> cspec_pb2_grpc.CspecStub:
    return cspec_pb2_grpc.CspecStub(channel.to_hatch())


def gene_disease() -> gene_disease_pb2_grpc.GeneDiseaseStub:
    return gene_disease_pb2_grpc.GeneDiseaseStub(channel.to_hatch())


def gnomad() -> gnomad_pb2_grpc.GnomadStub:
    return gnomad_pb2_grpc.GnomadStub(channel.to_hatch())


def hello() -> hello_pb2_grpc.HelloStub:
    return hello_pb2_grpc.HelloStub(channel.to_hatch())


def mavedb() -> mavedb_pb2_grpc.MaveDbStub:
    return mavedb_pb2_grpc.MaveDbStub(channel.to_hatch())


def splice() -> splice_pb2_grpc.SpliceStub:
    return splice_pb2_grpc.SpliceStub(channel.to_hatch())


def transcript() -> transcript_pb2_grpc.TranscriptStub:
    return transcript_pb2_grpc.TranscriptStub(channel.to_hatch())


def variant() -> variant_pb2_grpc.VariantStub:
    return variant_pb2_grpc.VariantStub(channel.to_hatch())


def vep() -> vep_pb2_grpc.VepStub:
    return vep_pb2_grpc.VepStub(channel.to_hatch())
