"""The per-session bare repository: a cache of the store, and the thing git actually serves.

A cache in the strict sense — never the source of truth — so `sync` force-updates local refs to
whatever the store says and deletes refs the store no longer has. Design:
`docs/design/sheaf.md`.
"""

from __future__ import annotations

import dataclasses
import json
import os
import pathlib
import subprocess
import sys
from collections.abc import Iterable, Mapping
from concurrent import futures

from themis.sheaf import backends
from themis.sheaf import store as store_mod

SYNC_STATE_FILE = 'sheaf-sync.json'
HOOK_NAME = 'pre-receive'
# One task per pack, so in-flight memory is bounded by concurrency x pack size.
DEFAULT_SYNC_CONCURRENCY = 16

# The directory `themis` lives in, baked into the generated hook below as its import path.
_IMPORT_ROOT = pathlib.Path(__file__).resolve().parents[3]

_HOOK_SOURCE = '''#!{python}
"""Generated by sheaf. Rejects a push whose compare-and-swap would clobber a concurrent one."""
import sys

# The server hands git http-backend a scrubbed environment, so PYTHONPATH does not reach here and
# the import path is baked in at generation time instead.
sys.path[:0] = {syspath!r}

from themis.sheaf.wire.hook import main

sys.exit(main())
'''


@dataclasses.dataclass(frozen=True)
class SyncState:
    """What the hook needs to know about the sync that produced the refs the client saw."""

    generation: int | None
    repo: str
    backend: dict[str, str]

    def to_json(self) -> str:
        """Serialise for the hook."""
        return json.dumps({'generation': self.generation, 'repo': self.repo, 'backend': self.backend})

    @classmethod
    def load(cls, path: str | os.PathLike[str]) -> SyncState:
        """Read the state written by the most recent sync.

        Raises:
            KeyError: If the file is missing a field, which means it was not written by `to_json`.
        """
        payload = json.loads(pathlib.Path(path).read_text('utf-8'))
        return cls(generation=payload['generation'], repo=payload['repo'], backend=payload['backend'])


def git(*args: str, cwd: str | os.PathLike[str], stdin: bytes | None = None) -> bytes:
    """Run a git command, returning stdout.

    Raises:
        RuntimeError: If git exits non-zero, with its stderr attached.
    """
    result = subprocess.run(  # noqa: S603
        ['git', *args],  # noqa: S607
        cwd=cwd,
        input=stdin,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f'git {" ".join(args)} failed: {result.stderr.decode(errors="replace")}')
    return result.stdout


class BareRepo:
    """A bare git repository mirroring one sheaf repository."""

    def __init__(
        self,
        store: store_mod.Store,
        path: str | os.PathLike[str],
        *,
        concurrency: int = DEFAULT_SYNC_CONCURRENCY,
    ) -> None:
        self.store = store
        self.path = pathlib.Path(path)
        self.concurrency = max(1, concurrency)
        self._installed_dir = self.path / 'sheaf-installed'

    def ensure(self) -> None:
        """Create and configure the repository, finishing a half-built one.

        Only `git init` is conditional; every step after it is idempotent and re-run on each call.
        `init` writes `HEAD` first and the hook last, so a process that dies in between — SIGTERM
        mid-request, OOM, a full disk — leaves a mirror that looks built and has no `pre-receive`.
        Receive-pack with no hook accepts the push, moves the mirror's refs and publishes nothing:
        `git push` reports success, the next `sync()` force-resets the refs, and the commit is gone.
        Protected paths go unchecked over the same window, since the hook is where both are decided.
        """
        if not (self.path / 'HEAD').exists():
            self.path.mkdir(parents=True, exist_ok=True)
            git('init', '--bare', '--quiet', str(self.path), cwd=self.path.parent)
        # Push over HTTP is off by default; a stale push must reach the hook, not a 403.
        git('config', 'http.receivepack', 'true', cwd=self.path)
        # The repo is a per-session cache, so it needs neither a reflog nor auto-gc.
        git('config', 'gc.auto', '0', cwd=self.path)
        # Off by default in git; with it on, receive-pack refuses a malformed object before the
        # pre-receive hook is invoked at all.
        git('config', 'receive.fsckObjects', 'true', cwd=self.path)
        self._installed_dir.mkdir(exist_ok=True)
        self._write_hook()

    def _write_hook(self) -> None:
        hook = self.path / 'hooks' / HOOK_NAME
        hook.parent.mkdir(parents=True, exist_ok=True)
        hook.write_text(_HOOK_SOURCE.format(python=sys.executable, syspath=[str(_IMPORT_ROOT)]), 'utf-8')
        hook.chmod(0o755)

    @property
    def sync_state_path(self) -> pathlib.Path:
        """Where the hook reads the generation the client's view was built from."""
        return self.path / SYNC_STATE_FILE

    def installed(self) -> set[str]:
        """Pack ids whose objects the object database can still read.

        A marker is a hardlink to the packfile git indexed, not a note about it, so the link count
        answers the question directly: two names means git still has its own, one means git deleted
        it — `git repack -a -d` drops every pack it consolidated, along with any object no ref
        reaches. The bytes survive under this link either way, which is what `install` re-indexes
        from instead of fetching them again.
        """
        return {marker.name for marker in self._markers() if marker.stat().st_nlink >= 2}

    def _markers(self) -> list[pathlib.Path]:
        """Every marker, live or orphaned."""
        return sorted(self._installed_dir.iterdir()) if self._installed_dir.is_dir() else []

    def sync(self) -> store_mod.Snapshot:
        """Bring the bare repo up to the store's current state and record the generation."""
        self.ensure()
        snapshot = self.store.read()

        self.install(ident for ident in snapshot.packs if ident not in self.installed())
        self._write_refs(snapshot)
        self._point_head(snapshot)
        state = SyncState(
            generation=snapshot.generation,
            repo=self.store.repo,
            backend=backends.descriptor_for(self.store.backend),
        )
        self.sync_state_path.write_text(state.to_json(), 'utf-8')
        return snapshot

    def install(self, idents: Iterable[str]) -> None:
        """Fetch and index the named packs concurrently.

        Concurrent `git index-pack` invocations against one repository are safe: each writes a
        uniquely named temporary and renames to a filename derived from the pack's own checksum,
        and none of them touches a ref. An exception in any worker propagates, because a
        half-hydrated mirror must not be presented as synced.
        """
        pending = list(idents)
        if not pending:
            return

        def fetch_and_index(ident: str) -> None:
            marker = self._installed_dir / ident
            # An orphaned marker is this pack, kept alive by its own link after a repack discarded
            # git's copy, so the mirror repairs itself from disk rather than from the store.
            data = marker.read_bytes() if marker.exists() else self.store.fetch_pack(ident)
            # `index-pack --stdin` copies the pack in under its canonical name and builds the index,
            # which is what makes a delta-compressed pack written by real git readable here. It
            # reports that name, which is the only way to know which file to link the marker to.
            reported = git('index-pack', '--stdin', cwd=self.path, stdin=data).decode().split()
            marker.unlink(missing_ok=True)
            os.link(self.path / 'objects' / 'pack' / f'pack-{reported[-1]}.pack', marker)

        if len(pending) == 1:
            fetch_and_index(pending[0])
            return
        with futures.ThreadPoolExecutor(max_workers=min(self.concurrency, len(pending))) as pool:
            for done in [pool.submit(fetch_and_index, ident) for ident in pending]:
                done.result()

    def adopt(self, packs: Mapping[str, pathlib.Path]) -> None:
        """Point the markers at `packs`, dropping every marker they do not name.

        For a local repack, whose output is already in the object database and so needs no fetch.
        Dropping the rest is what frees the packs it consolidated: their bytes outlive git's own
        copy precisely because a marker still links them, so nothing is reclaimed until the
        manifest that named them is gone. Safe only once that manifest is published — until then
        those links are the mirror's repair material.

        Args:
            packs: Pack id to the packfile in this mirror holding it.
        """
        self._installed_dir.mkdir(exist_ok=True)
        for stale in self._markers():
            stale.unlink()
        for ident, path in packs.items():
            os.link(path, self._installed_dir / ident)

    def local_packs(self) -> list[pathlib.Path]:
        """Packfiles currently in the mirror's object database."""
        return sorted((self.path / 'objects' / 'pack').glob('*.pack'))

    def repack(self) -> list[pathlib.Path]:
        """Consolidate the object database into as few packs as git will produce."""
        git('repack', '-a', '-d', '-q', cwd=self.path)
        return self.local_packs()

    def _write_refs(self, snapshot: store_mod.Snapshot) -> None:
        """Force local refs to match the store, deleting any the store no longer has."""
        commands = []
        for ref, sha in sorted(snapshot.refs.items()):
            commands.append(f'update {ref} {sha}\n')
        for ref in sorted(set(self.local_refs()) - set(snapshot.refs)):
            commands.append(f'delete {ref}\n')
        if not commands:
            return
        payload = 'start\n' + ''.join(commands) + 'prepare\ncommit\n'
        git('update-ref', '--stdin', cwd=self.path, stdin=payload.encode())

    def _point_head(self, snapshot: store_mod.Snapshot) -> None:
        """Aim HEAD at a branch the store actually has.

        `git init --bare` picks HEAD from the host's `init.defaultBranch`, so a mirror created on a
        machine defaulting to `master` advertises a HEAD pointing at nothing, and a client clones
        the refs and checks out an empty tree with no error at all. Receive-pack sets HEAD on an
        unborn repository, so this only shows up when hydrating a store that is already populated.
        """
        branches = sorted(ref for ref in snapshot.refs if ref.startswith('refs/heads/'))
        if not branches:
            return
        current = git('symbolic-ref', 'HEAD', cwd=self.path).decode().strip()
        if current in snapshot.refs:
            return
        preferred = 'refs/heads/main' if 'refs/heads/main' in branches else branches[0]
        git('symbolic-ref', 'HEAD', preferred, cwd=self.path)

    def local_refs(self) -> dict[str, str]:
        """Refs currently in the bare repo."""
        out = git('for-each-ref', '--format=%(refname) %(objectname)', cwd=self.path).decode()
        refs = {}
        for line in out.splitlines():
            name, _, sha = line.partition(' ')
            if name:
                refs[name] = sha
        return refs

    def pack_for(self, new_shas: list[str]) -> bytes:
        """Build a self-contained pack of everything reachable from `new_shas` but not published.

        The exclusion set is the bare repo's refs, read before any of them move — a pre-receive hook
        runs pre-update — so it is exactly what the store already holds. A pushed sha that is
        already one of those values stays excluded: `git push origin main:refs/heads/feature`
        creates a ref at a published commit, and dropping it from the exclusion set would leave the
        rev list an unbounded `X` and re-pack the entire object database. Deriving the pack this way
        rather than reaching into git's quarantine directory keeps it independent of
        `receive.unpackLimit`, which would otherwise explode a small push into loose objects and
        leave no pack to upload. No `--thin`, so the pack stands alone and any reader can index it.
        """
        excluded = sorted(set(self.local_refs().values()))
        revs = ''.join(f'{sha}\n' for sha in new_shas) + ''.join(f'^{sha}\n' for sha in excluded)
        return git('pack-objects', '--revs', '--stdout', cwd=self.path, stdin=revs.encode())
