# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: features.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x61tures.proto\x12\x08\x66\x65\x61tures\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\nEnumHolder\x12 \n\x06\x63olour\x18\x01 \x01(\x0e\x32\x10.features.Colour\"X\n\x0eOptionalHolder\x12\x16\n\x0erequired_field\x18\x01 \x01(\t\x12\x1b\n\x0eoptional_field\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_optional_field\"1\n\rDefaultHolder\x12\x14\n\x07\x66lagged\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_flagged\"\x16\n\x05Inner\x12\r\n\x05value\x18\x01 \x01(\t\"\'\n\x05Outer\x12\x1e\n\x05inner\x18\x01 \x01(\x0b\x32\x0f.features.Inner\">\n\x0b\x41rrayHolder\x12\x0c\n\x04tags\x18\x01 \x03(\t\x12!\n\x07palette\x18\x02 \x03(\x0e\x32\x10.features.Colour\"d\n\x0cScalarHolder\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\r\n\x05ratio\x18\x02 \x01(\x01\x12(\n\x04when\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04link\x18\x04 \x01(\t*&\n\x06\x43olour\x12\x07\n\x03red\x10\x00\x12\t\n\x05green\x10\x01\x12\x08\n\x04\x62lue\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLOUR']._serialized_start=481
  _globals['_COLOUR']._serialized_end=519
  _globals['_ENUMHOLDER']._serialized_start=61
  _globals['_ENUMHOLDER']._serialized_end=107
  _globals['_OPTIONALHOLDER']._serialized_start=109
  _globals['_OPTIONALHOLDER']._serialized_end=197
  _globals['_DEFAULTHOLDER']._serialized_start=199
  _globals['_DEFAULTHOLDER']._serialized_end=248
  _globals['_INNER']._serialized_start=250
  _globals['_INNER']._serialized_end=272
  _globals['_OUTER']._serialized_start=274
  _globals['_OUTER']._serialized_end=313
  _globals['_ARRAYHOLDER']._serialized_start=315
  _globals['_ARRAYHOLDER']._serialized_end=377
  _globals['_SCALARHOLDER']._serialized_start=379
  _globals['_SCALARHOLDER']._serialized_end=479
# @@protoc_insertion_point(module_scope)
