# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""Generated sandbox agent-exposure surface: the methods the guest may reach through the hatch."""

from __future__ import annotations

GUEST_METHODS = frozenset(
    {
        '/themis.rpc.clinvar.ClinVar/DescribeVariant',
        '/themis.rpc.clinvar.ClinVar/SearchCodingSpan',
        '/themis.rpc.cspec.Cspec/ListSpecifications',
        '/themis.rpc.gene_disease.GeneDisease/DescribeGene',
        '/themis.rpc.gnomad.Gnomad/DescribeVariant',
        '/themis.rpc.hello.Hello/SayHello',
        '/themis.rpc.literature.Literature/FetchPubmedArticles',
        '/themis.rpc.literature.Literature/GetMarkdown',
        '/themis.rpc.literature.Literature/ListLitVarEntities',
        '/themis.rpc.literature.Literature/MaybeIngestPapers',
        '/themis.rpc.literature.Literature/PollFullTexts',
        '/themis.rpc.literature.Literature/SearchEuropePmc',
        '/themis.rpc.literature.Literature/SearchLitVar',
        '/themis.rpc.literature.Literature/Validate',
        '/themis.rpc.mavedb.MaveDb/DescribeVariant',
        '/themis.rpc.splice.Splice/PredictDeltas',
        '/themis.rpc.splice.Splice/PredictSkipOutcome',
        '/themis.rpc.transcript.Transcript/AssessExonRelevance',
        '/themis.rpc.transcript.Transcript/GetStructure',
        '/themis.rpc.variant.Variant/Normalize',
        '/themis.rpc.vep.Vep/Annotate',
    }
)
