# @generated by tools.schema.regen from `option (themis.rpc.agent_exposed)` — do not edit.
# Regenerate: uv run --group codegen python -m tools.schema.regen
# Design: docs/design/sandbox-rpc-exposure.md
"""Generated sandbox agent-exposure surface: the methods the guest may reach through the hatch."""

from __future__ import annotations

GUEST_METHODS = frozenset(
    {
        '/themis.rpc.hello.Hello/SayHello',
    }
)
